/* CODE GENERATED BY SPOCK 0 */
var t518 = function (k294) {
 var t519 = function (k295, t1, t2) {	// qsa
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t520 = t1.querySelectorAll(t2);
   return k295(t520);
  }
 };
 ___qsa = t519;	// set! qsa
 var t522 = function (k296, t3, t4) {	// qs
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t523 = t3.querySelector(t4);
   return k296(t523);
  }
 };
 ___qs = t522;	// set! qs
 var t525 = function (k297, t5, t6) {	// dqsa
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t526 = document.body.querySelectorAll(t6);
   return k297(t526);
  }
 };
 ___dqsa = t525;	// set! dqsa
 var t528 = function (k298, t7, t8) {	// dqs
  var r = SPOCK.count(arguments);
  if(r) return r;
  return ___qs(k298, document.body, t8);
 };
 ___dqs = t528;	// set! dqs
 var t530 = function (k299, t9) {	// log
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t531 = console.log(t9);
   return k299(t531);
  }
 };
 ___log = t530;	// set! log
 var t533 = function (k300, t10) {	// alert
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t534 = window.alert(t10);
   return k300(t534);
  }
 };
 ___alert = t533;	// set! alert
 var t536 = function (k301, t11) {	// get-id
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t537 = document.getElementById(t11);
   return k301(t537);
  }
 };
 ___get_2did = t536;	// set! get-id
 var t539 = function (k302, t12, t13, t14) {	// new-element
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t540 = document.createElement(t12);
  var t15 = t540;
  var t541 = t15.classList.add(t14);
  var t542 = function (t303) {
   return k302(t15);
  };
  var t544 = function (k304, t16) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   loop: while(true) {
    var t545 = t15.appendChild(t16);
    return k304(t545);
   }
  };
  return ___map(t542, t544, t13);
 };
 ___new_2delement = t539;	// set! new-element
 var t548 = function (k305, t17) {	// <text>
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t549 = document.createTextNode(t17);
   return k305(t549);
  }
 };
 ____3ctext_3e = t548;	// set! <text>
 var t551 = function (k306, t18) {	// remove
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t552 = function(k553, x) { return k553(x.parentNode); }
  var t554 = function (t307) {
   var t555 = t307.removeChild(t18);
   return k306(t555);
  };
  return t552(t554, t18);
 };
 ___remove = t551;	// set! remove
 var t558 = function (k308, t19, t20) {	// insert-before
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t559 = function(k560, x) { return k560(x.parentNode); }
  var t561 = function (t309) {
   var t562 = t309.insertBefore(t19, t20);
   return k308(t562);
  };
  return t559(t561, t20);
 };
 ___insert_2dbefore = t558;	// set! insert-before
 var t565 = function (k310, t21, t22) {	// replace
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t566 = function(k567, x) { return k567(x.parentNode); }
  var t568 = function (t311) {
   var t569 = t311.replaceChild(t21, t22);
   return k310(t569);
  };
  return t566(t568, t22);
 };
 ___replace = t565;	// set! replace
 var t572 = function (k312, t23, t24) {	// append-child
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t573 = t23.appendChild(t24);
   return k312(t573);
  }
 };
 ___append_2dchild = t572;	// set! append-child
 var t575 = function (k313, t25, t26) {	// set-html
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t25.innerHTML = t26;
   return k313(t26);
  }
 };
 ___set_2dhtml = t575;	// set! set-html
 var t577 = new diffDOM();
 ___dd = t577;	// set! dd
 var t578 = function (k314, t27, t28) {	// patch
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t580 = ___dd.diff(t27, t28);
   var t579 = ___dd.apply(t27, t580);
   return k314(t579);
  }
 };
 ___patch = t578;	// set! patch
 var t582 = function (k315) {	// spock-elements
  loop: while(true) {
   var t584 = document.body.querySelectorAll("*[spock]");
   var t583 = Array.prototype.slice.call(t584);
   return k315(t583);
  }
 };
 ___spock_2delements = t582;	// set! spock-elements
 var t586 = function (k316, t29, t30, t31) {	// add-event-listener
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t587 = t30.addEventListener(t29, t31);
   return k316(t587);
  }
 };
 ___add_2devent_2dlistener = t586;	// set! add-event-listener
 var t589 = function (k317, t32, t33) {	// set-click
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t32.onclick = t33;
   return k317(t32);
  }
 };
 ___set_2dclick = t589;	// set! set-click
 var t591 = function (k318, t34, t35) {	// ajax
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t592 = new XMLHttpRequest();
  var t36 = t592;
  var t593 = function (t319) {
   var t594 = t36.open(t34, t35, true);
   var t595 = function (k320) {	// t37
    var t596 = alert(5);
    var t597 = function(k598, x) { return k598(x.responseText); }
    var t599 = function (t321) {
     return ___log(k320, t321);
    };
    return t597(t599, t36);
   };
   var t37 = t595;
   var t602 = SPOCK.callback(t37);
   t36.onreadystatechange = t602;
   var t603 = t36.send();
   return k318(t603);
  };
  return ___log(t593, t36);
 };
 ___ajax = t591;	// set! ajax
 var t606 = function (k322, t38, t39) {	// register-callback
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t607 = function (t323) {	// t324
   var t40 = t323;
   var t608 = SPOCK.intern("callback");
   return ___put_21(k322, t40, t608, t39);
  };
  var t324 = t607;
  var t41 = t38;
  var t611 = typeof(t41);
  var t43 = t611;
  var t44 = "string";
  var t612 = (t43) === (t44);
  var t42 = t612;
  var t613;
  if(t42 !== false) {
   t613 = t42;
  }
  else {
   var t614 = (t41) instanceof SPOCK.String ;
   t613 = t614;
  }
  var t610;
  if(t613 !== false) {
   return ___string_2d_3esymbol(t324, t38);
  }
  else {
   return t324(t38);
  }
 };
 ___register_2dcallback = t606;	// set! register-callback
 var t617 = function (k325, t45) {	// get-callback
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t618 = function (t326) {	// t327
   var t46 = t326;
   var t619 = SPOCK.intern("callback");
   return ___get(k325, t46, t619);
  };
  var t327 = t618;
  var t47 = t45;
  var t622 = typeof(t47);
  var t49 = t622;
  var t50 = "string";
  var t623 = (t49) === (t50);
  var t48 = t623;
  var t624;
  if(t48 !== false) {
   t624 = t48;
  }
  else {
   var t625 = (t47) instanceof SPOCK.String ;
   t624 = t625;
  }
  var t621;
  if(t624 !== false) {
   return ___string_2d_3esymbol(t327, t45);
  }
  else {
   return t327(t45);
  }
 };
 ___get_2dcallback = t617;	// set! get-callback
 var t628 = function (k328) {	// waiting
  loop: while(true) {
   return k328(false);
  }
 };
 ___waiting = t628;	// set! waiting
 ___call_2fcc = ___call_2dwith_2dcurrent_2dcontinuation;	// set! call/cc
 var t630 = null;
 ____2aqueue_2a = t630;	// set! *queue*
 var t631 = function (k329, t51) {	// *enqueue*
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t632 = function (t332) {
   var t52 = t332;
   var t331 = t52;
   var t633 = function (t330) {
    ____2aqueue_2a = t330;	// set! *queue*
    return k329(undefined);
   };
   return ___append(t633, ____2aqueue_2a, t331);
  };
  return ____25list(t632, t51);
 };
 ____2aenqueue_2a = t631;	// set! *enqueue*
 var t637 = function (k333) {	// *dequeue*
  loop: while(true) {
   var t54 = ____2aqueue_2a;
   var t55 = t54;
   var t638 = t55.car;
   var t53 = t638;
   var t56 = ____2aqueue_2a;
   var t57 = t56;
   var t639 = t57.cdr;
   ____2aqueue_2a = t639;	// set! *queue*
   return k333(t53);
  }
 };
 ____2adequeue_2a = t637;	// set! *dequeue*
 var t641 = function (k334) {	// yield
  var t58 = ____2aqueue_2a;
  var t59 = t58;
  var t643 = null;
  var t60 = t643;
  var t644 = (t59) === (t60);
  var t642;
  if(t644 !== false) {
   return ___waiting(k334);
  }
  else {
   var t646 = function (t335) {
    var t61 = t335;
    var t647 = function (t336) {
     var t648 = function (t337) {
      return t337(k334);
     };
     return t61(t648);
    };
    return ___print(t647, "YIELDING");
   };
   return ____2adequeue_2a(t646);
  }
 };
 ___yield = t641;	// set! yield
 var t653 = function (k338, t62, t63) {	// assoc-val
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t654 = function (t339) {
   var t64 = t339;
   var t65 = t64;
   var t655 = t65.cdr;
   return k338(t655);
  };
  return ___assoc(t654, t62, t63);
 };
 ___assoc_2dval = t653;	// set! assoc-val
 ___merge_2dbindings = ___append;	// set! merge-bindings
 var t658 = function (k340, t66, t67) {	// get-binding
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t659 = function (t341) {
   var t68 = t341;
   var t660;
   if(t68 !== false) {
    var t69 = t68;
    var t70 = t69;
    var t661 = t70.cdr;
    t660 = t661;
   }
   else {
    t660 = false;
   }
   return k340(t660);
  };
  return ___assoc(t659, t66, t67);
 };
 ___get_2dbinding = t658;	// set! get-binding
 var t664 = function (k342, t71, t72) {	// send-bindings
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t665 = function (t343) {
   return t343(k342, t72);
  };
  var t667 = SPOCK.intern("continuations");
  return ___get(t665, t71, t667);
 };
 ___send_2dbindings = t664;	// set! send-bindings
 var t669 = function (k344, t73, t74) {	// three-way-split
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t75 = undefined;
  var t670 = function (k345, t76, t77, t78, t79, t80) {	// t75
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t81 = t77;
   var t82 = t81;
   var t672 = null;
   var t83 = t672;
   var t673 = (t82) === (t83);
   var t671;
   if(t673 !== false) {
    var t674 = function (t347) {
     var t675 = function (t346) {
      var t84 = t346;
      return k345(t84);
     };
     return ____25list(t675, t347, t79, t80);
    };
    return ___append(t674, t76, t78);
   }
   else {
    var t86 = t77;
    var t87 = t86;
    var t679 = t87.car;
    var t85 = t679;
    var t88 = undefined;
    var t680 = function (k348, t89, t90) {	// t88
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t91 = t89;
     var t92 = t91;
     var t682 = null;
     var t93 = t682;
     var t683 = (t92) === (t93);
     var t681;
     if(t683 !== false) {
      var t94 = t77;
      var t95 = t94;
      var t684 = t95.cdr;
      var t96 = t85;
      var t97 = t80;
      var t685 = new SPOCK.Pair(t96, t97);
      return t75(k348, t90, t684, t78, t79, t685);
     }
     else {
      var t99 = t89;
      var t100 = t99;
      var t687 = t100.car;
      var t98 = t687;
      var t101 = t85;
      var t102 = t98;
      var t689 = SPOCK.equalp(t101, t102);
      var t688;
      if(t689 !== false) {
       var t690 = function (t349) {
        var t105 = t77;
        var t106 = t105;
        var t691 = t106.cdr;
        var t107 = t85;
        var t108 = t79;
        var t692 = new SPOCK.Pair(t107, t108);
        return t75(k348, t349, t691, t78, t692, t80);
       };
       var t103 = t89;
       var t104 = t103;
       var t694 = t104.cdr;
       return ___append(t690, t90, t694);
      }
      else {
       var t109 = t89;
       var t110 = t109;
       var t696 = t110.cdr;
       var t111 = t98;
       var t112 = t90;
       var t697 = new SPOCK.Pair(t111, t112);
       return t88(k348, t696, t697);
      }
      t681 = t688;
     }
    };
    t88 = t680;	// set! t88
    var t699 = null;
    return t88(k345, t76, t699);
   }
  };
  t75 = t670;	// set! t75
  var t701 = null;
  var t702 = null;
  var t703 = null;
  return t75(k344, t73, t74, t701, t702, t703);
 };
 ___three_2dway_2dsplit = t669;	// set! three-way-split
 var t705 = function (k350, t113, t114) {	// merge-alist-sets
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t116 = t114;
  var t117 = t116;
  var t706 = t117.car;
  var t115 = t706;
  var t118 = undefined;
  var t707 = function (k351, t119, t120, t121) {	// t118
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t123 = t120;
   var t124 = t123;
   var t709 = null;
   var t125 = t709;
   var t710 = (t124) === (t125);
   var t122 = t710;
   var t711;
   if(t122 !== false) {
    t711 = t122;
   }
   else {
    var t126 = t119;
    var t127 = t126;
    var t712 = null;
    var t128 = t712;
    var t713 = (t127) === (t128);
    t711 = t713;
   }
   var t708;
   if(t711 !== false) {
    var t714 = function (t354) {
     var t133 = t354;
     var t353 = t133;
     var t131 = t353;
     var t132 = t120;
     var t715 = new SPOCK.Pair(t131, t132);
     var t352 = t715;
     var t129 = t352;
     var t130 = t121;
     var t716 = new SPOCK.Pair(t129, t130);
     return k351(t716);
    };
    return ____25list(t714, t115);
   }
   else {
    var t135 = t119;
    var t137 = t135;
    var t138 = t137;
    var t719 = t138.car;
    var t136 = t719;
    var t139 = t136;
    var t720 = t139.car;
    var t134 = t720;
    var t141 = t119;
    var t143 = t141;
    var t144 = t143;
    var t721 = t144.car;
    var t142 = t721;
    var t145 = t142;
    var t722 = t145.cdr;
    var t140 = t722;
    var t723 = function (t355) {
     var t146 = t355;
     var t148 = t146;
     var t149 = t148;
     var t724 = t149.car;
     var t147 = t724;
     var t151 = t146;
     var t153 = t151;
     var t154 = t153;
     var t725 = t154.cdr;
     var t152 = t725;
     var t155 = t152;
     var t726 = t155.car;
     var t150 = t726;
     var t727 = function (t356) {
      var t156 = t356;
      var t728 = function (t359) {
       var t159 = t359;
       var t358 = t159;
       var t729 = function (t357) {
        var t157 = t119;
        var t158 = t157;
        var t730 = t158.cdr;
        return t118(k351, t730, t156, t357);
       };
       return ___append(t729, t358, t121);
      };
      var t160 = t134;
      var t161 = t147;
      var t733 = new SPOCK.Pair(t160, t161);
      var t164 = t115;
      var t165 = t134;
      var t734 = new SPOCK.Pair(t164, t165);
      var t162 = t734;
      var t163 = t150;
      var t735 = new SPOCK.Pair(t162, t163);
      return ____25list(t728, t733, t735);
     };
     return ___caddr(t727, t146);
    };
    return ___three_2dway_2dsplit(t723, t140, t120);
   }
  };
  t118 = t707;	// set! t118
  var t166 = t114;
  var t167 = t166;
  var t739 = t167.cdr;
  var t740 = null;
  return t118(k350, t113, t739, t740);
 };
 ___merge_2dalist_2dsets = t705;	// set! merge-alist-sets
 var t742 = function (k360, t168) {	// merge-continuation-lists
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t169 = undefined;
  var t743 = function (k361, t170, t171) {	// t169
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t172 = t171;
   var t173 = t172;
   var t745 = null;
   var t174 = t745;
   var t746 = (t173) === (t174);
   var t744;
   if(t746 !== false) {
    return k361(t170);
   }
   else {
    var t748 = function (t362) {
     var t177 = t171;
     var t178 = t177;
     var t749 = t178.cdr;
     return t169(k361, t362, t749);
    };
    var t175 = t171;
    var t176 = t175;
    var t751 = t176.car;
    return ___merge_2dalist_2dsets(t748, t170, t751);
   }
  };
  t169 = t743;	// set! t169
  var t753 = null;
  return t169(k360, t753, t168);
 };
 ___merge_2dcontinuation_2dlists = t742;	// set! merge-continuation-lists
 var t755 = function (k363, t179) {	// merge-continuation-lists2
  var r = SPOCK.count(arguments);
  if(r) return r;
  return ___append(k363, t179);
 };
 ___merge_2dcontinuation_2dlists2 = t755;	// set! merge-continuation-lists2
 var t757 = function (k364, t180) {	// send-vars
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t758 = function (t372) {
   var t759 = function (t371) {
    var t760 = function (t365) {
     var t761 = function (t366) {
      return ___yield(k364);
     };
     return ___print(t761, "QUEUE: ", ____2aqueue_2a);
    };
    var t764 = function (k367, t181) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t765 = function (t368) {
      var t184 = t181;
      var t185 = t184;
      var t766 = t185.car;
      var t182 = t766;
      var t186 = t181;
      var t187 = t186;
      var t767 = t187.cdr;
      var t183 = t767;
      var t189 = t183;
      var t190 = t189;
      var t769 = null;
      var t191 = t769;
      var t770 = (t190) === (t191);
      var t188 = t770;
      var t771;
      if(t188 !== false) {
       t771 = false;
      }
      else {
       t771 = true;
      }
      var t768;
      if(t771 !== false) {
       var t772 = function (k369, t192) {
        var r = SPOCK.count(arguments);
        if(r) return r;
        var t773 = function (k370) {
         return t192(k370, t180);
        };
        return ____2aenqueue_2a(k369, t773);
       };
       return ___map(k367, t772, t183);
      }
      else {
       return k367(undefined);
      }
     };
     return ___print(t765, "CONTINUATIONS: ", t181);
    };
    return ___map(t760, t764, t371);
   };
   return ___merge_2dcontinuation_2dlists(t759, t372);
  };
  var t781 = function (k373, t193) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t195 = t193;
   var t196 = t195;
   var t782 = t196.car;
   var t194 = t782;
   var t197 = t194;
   var t783 = function (t374) {
    var t198 = t374;
    var t784 = new SPOCK.Pair(t197, t198);
    return k373(t784);
   };
   var t786 = SPOCK.intern("continuations");
   return ___get(t783, t194, t786);
  };
  return ___map(t758, t781, t180);
 };
 ___send_2dvars = t757;	// set! send-vars
 var t789 = function (k375, t199) {	// init
  var r = SPOCK.count(arguments);
  if(r) return r;
  ____2ainits_2a = t199;	// set! *inits*
  var t790 = function (t381) {
   var t791 = function (t376) {
    var t792 = function (t377) {
     return ___print(k375, "waiting...");
    };
    var t794 = function (k378, t202) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     loop: while(true) {
      ___waiting = t202;	// set! waiting
      return k378(undefined);
     }
    };
    return ___call_2fcc(t792, t794);
   };
   var t797 = function (k379, t200) {
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t798 = t200.getAttribute("spock");
    var t201 = t798;
    var t799 = function (t380) {
     return t380(k379, t200);
    };
    return ___get_2dcallback(t799, t201);
   };
   return ___map(t791, t797, t381);
  };
  return ___spock_2delements(t790);
 };
 ___init = t789;	// set! init
 var t804 = function (k382, t203) {	// click1
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t805 = null;
  var t204 = t805;
  var t806 = function (t383) {
   var t205 = t383;
   var t807 = function (t387) {
    t204 = t387;	// set! t204
    var t384 = undefined;
    var t808 = function (t385) {
     return ___yield(k382);
    };
    var t810 = function (k386, t214) {	// t213
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t811 = new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("status"), "Loading..."), null);
     var t215 = t811;
     return ___send_2dvars(k386, t215);
    };
    var t213 = t810;
    var t813 = SPOCK.callback(t213);
    return ___set_2dclick(t808, t203, t813);
   };
   return ___merge_2dbindings(t807, t205, t204);
  };
  var t816 = function (k388, t206) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t817 = function (t398) {
    var t211 = t398;
    var t397 = t211;
    var t818 = function (t389) {
     var t819 = function (t390) {
      var t212 = t390;
      return k388(t212);
     };
     return ____25list(t819);
    };
    var t822 = function (k391, t207) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t823 = function (t396) {
      var t824 = function (t392) {
       var t208 = t206;
       var t825 = function (t395) {
        var t210 = t395;
        var t826;
        if(t210 !== false) {
         t826 = t210;
        }
        else {
         var t827 = null;
         t826 = t827;
        }
        var t394 = t826;
        var t209 = t394;
        var t828 = new SPOCK.Pair(t208, t209);
        var t393 = t828;
        var t829 = SPOCK.intern("continuations");
        return ___put_21(k391, t207, t829, t393);
       };
       var t831 = SPOCK.intern("continuations");
       return ___get(t825, t207, t831);
      };
      return ___print(t824, "putting ", t207, ": ", t206, " into ", t396);
     };
     var t834 = SPOCK.intern("continuations");
     return ___get(t823, t207, t834);
    };
    return ___map(t818, t822, t397);
   };
   return ____25list(t817);
  };
  return ___call_2fcc(t806, t816);
 };
 ___click1 = t804;	// set! click1
 return ___register_2dcallback(k294, "click1", ___click1);
};
SPOCK.run(t518);
var t840 = function (k399) {
 var t841 = function (k400, t216) {	// click2
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t842 = null;
  var t217 = t842;
  var t843 = function (t401) {
   var t218 = t401;
   var t844 = function (t408) {
    t217 = t408;	// set! t217
    var t402 = undefined;
    var t845 = function (t404) {
     var t226 = t404;
     var t846 = function (t403) {
      return ___yield(k400);
     };
     var t848 = function (k405, t228) {	// t227
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t849 = function (t407) {
       var t230 = t407;
       var t406 = t230;
       var t229 = t406;
       return ___send_2dvars(k405, t229);
      };
      var t851 = SPOCK.intern("count");
      var t231 = t851;
      var t233 = t226;
      var t234 = 1;
      var t852 = (t233)  +  (t234);
      var t232 = t852;
      var t853 = new SPOCK.Pair(t231, t232);
      return ____25list(t849, t853);
     };
     var t227 = t848;
     var t855 = SPOCK.callback(t227);
     return ___set_2dclick(t846, t216, t855);
    };
    var t857 = SPOCK.intern("count");
    return ___assoc_2dval(t845, t857, t217);
   };
   return ___merge_2dbindings(t844, t218, t217);
  };
  var t860 = function (k409, t219) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t861 = function (t420) {
    var t224 = t420;
    var t419 = t224;
    var t862 = function (t410) {
     var t863 = function (t412) {
      var t864 = function (t411) {
       var t225 = t411;
       return k409(t225);
      };
      return ____25list(t864, t412);
     };
     var t867 = SPOCK.intern("count");
     return ___assoc(t863, t867, ____2ainits_2a);
    };
    var t869 = function (k413, t220) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t870 = function (t418) {
      var t871 = function (t414) {
       var t221 = t219;
       var t872 = function (t417) {
        var t223 = t417;
        var t873;
        if(t223 !== false) {
         t873 = t223;
        }
        else {
         var t874 = null;
         t873 = t874;
        }
        var t416 = t873;
        var t222 = t416;
        var t875 = new SPOCK.Pair(t221, t222);
        var t415 = t875;
        var t876 = SPOCK.intern("continuations");
        return ___put_21(k413, t220, t876, t415);
       };
       var t878 = SPOCK.intern("continuations");
       return ___get(t872, t220, t878);
      };
      return ___print(t871, "putting ", t220, ": ", t219, " into ", t418);
     };
     var t881 = SPOCK.intern("continuations");
     return ___get(t870, t220, t881);
    };
    return ___map(t862, t869, t419);
   };
   var t884 = SPOCK.intern("count");
   return ____25list(t861, t884);
  };
  return ___call_2fcc(t843, t860);
 };
 ___click2 = t841;	// set! click2
 return ___register_2dcallback(k399, "click2", ___click2);
};
SPOCK.run(t840);
var t888 = function (k421) {
 var t889 = function (k422, t235, t236) {	// range
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t237 = t235;
  var t238 = t236;
  var t891 = SPOCK.equalp(t237, t238);
  var t890;
  if(t891 !== false) {
   var t892 = null;
   return k422(t892);
  }
  else {
   var t239 = t235;
   var t894 = function (t423) {
    var t240 = t423;
    var t895 = new SPOCK.Pair(t239, t240);
    return k422(t895);
   };
   var t241 = 1;
   var t242 = t235;
   var t897 = (t241)  +  (t242);
   return ___range(t894, t897, t236);
  }
 };
 ___range = t889;	// set! range
 var t899 = function (k424, t243) {	// click0
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t900 = null;
  var t244 = t900;
  var t901 = function (t425) {
   var t245 = t425;
   var t902 = function (t434) {
    t244 = t434;	// set! t244
    var t426 = undefined;
    var t903 = function (t428) {
     var t253 = t428;
     var t904 = function (t427) {
      return ___yield(k424);
     };
     var t906 = function (k429, t255) {	// t254
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t907 = SPOCK.intern("messages");
      var t258 = t907;
      var t908 = function (t433) {
       var t259 = t433;
       var t909 = new SPOCK.Pair(t258, t259);
       var t432 = t909;
       var t910 = function (t431) {
        var t257 = t431;
        var t430 = t257;
        var t256 = t430;
        return ___send_2dvars(k429, t256);
       };
       return ____25list(t910, t432);
      };
      return ___range(t908, 0, t253);
     };
     var t254 = t906;
     var t914 = SPOCK.callback(t254);
     return ___set_2dclick(t904, t243, t914);
    };
    var t916 = SPOCK.intern("count");
    return ___assoc_2dval(t903, t916, t244);
   };
   return ___merge_2dbindings(t902, t245, t244);
  };
  var t919 = function (k435, t246) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t920 = function (t446) {
    var t251 = t446;
    var t445 = t251;
    var t921 = function (t436) {
     var t922 = function (t438) {
      var t923 = function (t437) {
       var t252 = t437;
       return k435(t252);
      };
      return ____25list(t923, t438);
     };
     var t926 = SPOCK.intern("count");
     return ___assoc(t922, t926, ____2ainits_2a);
    };
    var t928 = function (k439, t247) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t929 = function (t444) {
      var t930 = function (t440) {
       var t248 = t246;
       var t931 = function (t443) {
        var t250 = t443;
        var t932;
        if(t250 !== false) {
         t932 = t250;
        }
        else {
         var t933 = null;
         t932 = t933;
        }
        var t442 = t932;
        var t249 = t442;
        var t934 = new SPOCK.Pair(t248, t249);
        var t441 = t934;
        var t935 = SPOCK.intern("continuations");
        return ___put_21(k439, t247, t935, t441);
       };
       var t937 = SPOCK.intern("continuations");
       return ___get(t931, t247, t937);
      };
      return ___print(t930, "putting ", t247, ": ", t246, " into ", t444);
     };
     var t940 = SPOCK.intern("continuations");
     return ___get(t929, t247, t940);
    };
    return ___map(t921, t928, t445);
   };
   var t943 = SPOCK.intern("count");
   return ____25list(t920, t943);
  };
  return ___call_2fcc(t901, t919);
 };
 ___click0 = t899;	// set! click0
 return ___register_2dcallback(k421, "click0", ___click0);
};
SPOCK.run(t888);
var t947 = function (k447) {
 var t948 = function (k448, t260) {	// single-render
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t949 = null;
  var t261 = t949;
  var t950 = function (t449) {
   var t262 = t449;
   var t951 = function (t463) {
    t261 = t463;	// set! t261
    var t450 = undefined;
    var t952 = function (t452) {
     var t270 = t452;
     var t953 = function (t462) {
      var t954 = function (t461) {
       var t273 = t461;
       var t460 = t273;
       var t955 = function (t453) {
        var t271 = t453;
        var t956 = t260.cloneNode(false);
        var t272 = t956;
        var t957 = function (t454) {
         var t958 = function (t455) {	// t457
          var t959 = function (t456) {
           t260 = t272;	// set! t260
           var t451 = undefined;
           return ___yield(k448);
          };
          return ___replace(t959, t272, t260);
         };
         var t457 = t958;
         var t962 = function (t458) {
          var t963;
          if(t458 !== false) {
           var t964 = function (k459, t274) {
            var r = SPOCK.count(arguments);
            if(r) return r;
            return ___append_2dchild(k459, t272, t274);
           };
           return ___for_2deach(t457, t964, t271);
          }
          else {
           return ___append_2dchild(t457, t272, t271);
          }
         };
         return ___list_3f(t962, t271);
        };
        return ___log(t957, t271);
       };
       return ___new_2delement(t955, "div", t460, "class");
      };
      return ____25list(t954, t462);
     };
     return ____3ctext_3e(t953, t270);
    };
    var t973 = SPOCK.intern("status");
    return ___assoc_2dval(t952, t973, t261);
   };
   return ___merge_2dbindings(t951, t262, t261);
  };
  var t976 = function (k464, t263) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t977 = function (t475) {
    var t268 = t475;
    var t474 = t268;
    var t978 = function (t465) {
     var t979 = function (t467) {
      var t980 = function (t466) {
       var t269 = t466;
       return k464(t269);
      };
      return ____25list(t980, t467);
     };
     var t983 = SPOCK.intern("status");
     return ___assoc(t979, t983, ____2ainits_2a);
    };
    var t985 = function (k468, t264) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t986 = function (t473) {
      var t987 = function (t469) {
       var t265 = t263;
       var t988 = function (t472) {
        var t267 = t472;
        var t989;
        if(t267 !== false) {
         t989 = t267;
        }
        else {
         var t990 = null;
         t989 = t990;
        }
        var t471 = t989;
        var t266 = t471;
        var t991 = new SPOCK.Pair(t265, t266);
        var t470 = t991;
        var t992 = SPOCK.intern("continuations");
        return ___put_21(k468, t264, t992, t470);
       };
       var t994 = SPOCK.intern("continuations");
       return ___get(t988, t264, t994);
      };
      return ___print(t987, "putting ", t264, ": ", t263, " into ", t473);
     };
     var t997 = SPOCK.intern("continuations");
     return ___get(t986, t264, t997);
    };
    return ___map(t978, t985, t474);
   };
   var t1000 = SPOCK.intern("status");
   return ____25list(t977, t1000);
  };
  return ___call_2fcc(t950, t976);
 };
 ___single_2drender = t948;	// set! single-render
 return ___register_2dcallback(k447, "single-render", ___single_2drender);
};
SPOCK.run(t947);
var t1004 = function (k476) {
 var t1005 = function (k477, t275) {	// map-render
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1006 = null;
  var t276 = t1006;
  var t1007 = function (t478) {
   var t277 = t478;
   var t1008 = function (t503) {
    t276 = t503;	// set! t276
    var t479 = undefined;
    var t1009 = function (t481) {
     var t285 = t481;
     var t1010 = function (t482) {
      var t286 = t482;
      var t1011 = function (t483) {
       var t287 = t483;
       var t1012 = t275.cloneNode(false);
       var t288 = t1012;
       var t1013 = function (t484) {
        var t1014 = function (t485) {	// t487
         var t1015 = function (t486) {
          t275 = t288;	// set! t275
          var t480 = undefined;
          return ___yield(k477);
         };
         return ___replace(t1015, t288, t275);
        };
        var t487 = t1014;
        var t1018 = function (t488) {
         var t1019;
         if(t488 !== false) {
          var t1020 = function (k489, t293) {
           var r = SPOCK.count(arguments);
           if(r) return r;
           return ___append_2dchild(k489, t288, t293);
          };
          return ___for_2deach(t487, t1020, t287);
         }
         else {
          return ___append_2dchild(t487, t288, t287);
         }
        };
        return ___list_3f(t1018, t287);
       };
       return ___log(t1013, t287);
      };
      var t1026 = function (k490, t289) {
       var r = SPOCK.count(arguments);
       if(r) return r;
       var t1027 = function (t493) {
        var t1028 = function (t494) {
         var t1029 = function (t502) {
          var t1030 = function (t501) {
           var t291 = t501;
           var t500 = t291;
           var t1031 = function (t496) {
            var t1032 = function (t495) {
             var t1033 = function (t492) {
              var t290 = t492;
              var t491 = t290;
              return ___new_2delement(k490, "div", t491, "class");
             };
             return ____25list(t1033, t493, t494, t495);
            };
            var t1036 = function (k497) {	// t292
             var t1037 = function (t499) {
              var t1038 = new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("status"), "reloading"), null);
              var t498 = t1038;
              return ___send_2dvars(k497, t498);
             };
             return ___print(t1037, "yay ", t289);
            };
            var t292 = t1036;
            var t1041 = SPOCK.callback(t292);
            return ___set_2dclick(t1032, t496, t1041);
           };
           return ___new_2delement(t1031, "button", t500, "class");
          };
          return ____25list(t1030, t502);
         };
         return ____3ctext_3e(t1029, "click me");
        };
        return ____3ctext_3e(t1028, t286);
       };
       return ____3ctext_3e(t1027, t289);
      };
      return ___map(t1011, t1026, t285);
     };
     var t1049 = SPOCK.intern("count");
     return ___assoc_2dval(t1010, t1049, t276);
    };
    var t1051 = SPOCK.intern("messages");
    return ___assoc_2dval(t1009, t1051, t276);
   };
   return ___merge_2dbindings(t1008, t277, t276);
  };
  var t1054 = function (k504, t278) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1055 = function (t516) {
    var t283 = t516;
    var t515 = t283;
    var t1056 = function (t505) {
     var t1057 = function (t507) {
      var t1058 = function (t508) {
       var t1059 = function (t506) {
        var t284 = t506;
        return k504(t284);
       };
       return ____25list(t1059, t507, t508);
      };
      var t1062 = SPOCK.intern("count");
      return ___assoc(t1058, t1062, ____2ainits_2a);
     };
     var t1064 = SPOCK.intern("messages");
     return ___assoc(t1057, t1064, ____2ainits_2a);
    };
    var t1066 = function (k509, t279) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1067 = function (t514) {
      var t1068 = function (t510) {
       var t280 = t278;
       var t1069 = function (t513) {
        var t282 = t513;
        var t1070;
        if(t282 !== false) {
         t1070 = t282;
        }
        else {
         var t1071 = null;
         t1070 = t1071;
        }
        var t512 = t1070;
        var t281 = t512;
        var t1072 = new SPOCK.Pair(t280, t281);
        var t511 = t1072;
        var t1073 = SPOCK.intern("continuations");
        return ___put_21(k509, t279, t1073, t511);
       };
       var t1075 = SPOCK.intern("continuations");
       return ___get(t1069, t279, t1075);
      };
      return ___print(t1068, "putting ", t279, ": ", t278, " into ", t514);
     };
     var t1078 = SPOCK.intern("continuations");
     return ___get(t1067, t279, t1078);
    };
    return ___map(t1056, t1066, t515);
   };
   var t1081 = SPOCK.intern("messages");
   var t1082 = SPOCK.intern("count");
   return ____25list(t1055, t1081, t1082);
  };
  return ___call_2fcc(t1007, t1054);
 };
 ___map_2drender = t1005;	// set! map-render
 return ___register_2dcallback(k476, "map-render", ___map_2drender);
};
SPOCK.run(t1004);
var t1086 = function (k517) {
 var t1087 = new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("status"), "Not loaded yet."), new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("messages"), new SPOCK.Pair(8, null)), new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("count"), 20), null)));
 return ___init(k517, t1087);
};
SPOCK.run(t1086);
SPOCK.flush();
/* END OF GENERATED CODE */
