/* CODE GENERATED BY SPOCK 0 */
var t752 = function (k410) {
 var t753 = function (k411, t1, t2) {	// qsa
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t754 = t1.querySelectorAll(t2);
   return k411(t754);
  }
 };
 ___qsa = t753;	// set! qsa
 var t756 = function (k412, t3, t4) {	// qs
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t757 = t3.querySelector(t4);
   return k412(t757);
  }
 };
 ___qs = t756;	// set! qs
 var t759 = function (k413, t5, t6) {	// dqsa
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t760 = document.body.querySelectorAll(t6);
   return k413(t760);
  }
 };
 ___dqsa = t759;	// set! dqsa
 var t762 = function (k414, t7, t8) {	// dqs
  var r = SPOCK.count(arguments);
  if(r) return r;
  return ___qs(k414, document.body, t8);
 };
 ___dqs = t762;	// set! dqs
 var t764 = function (k415, t9) {	// log
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t765 = console.log(t9);
   return k415(t765);
  }
 };
 ___log = t764;	// set! log
 var t767 = function (k416, t10) {	// alert
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t768 = window.alert(t10);
   return k416(t768);
  }
 };
 ___alert = t767;	// set! alert
 var t770 = function (k417, t11) {	// get-id
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t771 = document.getElementById(t11);
   return k417(t771);
  }
 };
 ___get_2did = t770;	// set! get-id
 var t773 = function (k418, t12) {	// remove-node
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t774 = function(k775, x) { return k775(x.parentNode); }
  var t776 = function (t419) {
   var t777 = t419.removeChild(t12);
   return k418(t777);
  };
  return t774(t776, t12);
 };
 ___remove_2dnode = t773;	// set! remove-node
 var t780 = function (k420, t13, t14) {	// insert-node-before
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t781 = function(k782, x) { return k782(x.parentNode); }
  var t783 = function (t421) {
   var t784 = t421.insertBefore(t13, t14);
   return k420(t784);
  };
  return t781(t783, t14);
 };
 ___insert_2dnode_2dbefore = t780;	// set! insert-node-before
 var t787 = function (k422, t15, t16) {	// replace-node
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t788 = function(k789, x) { return k789(x.parentNode); }
  var t790 = function (t423) {
   var t791 = t423.replaceChild(t15, t16);
   return k422(t791);
  };
  return t788(t790, t16);
 };
 ___replace_2dnode = t787;	// set! replace-node
 var t794 = function (k424, t17, t18) {	// node-append-child
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t795 = t17.appendChild(t18);
   return k424(t795);
  }
 };
 ___node_2dappend_2dchild = t794;	// set! node-append-child
 var t797 = function (k425, t19, t20) {	// set-html
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t19.innerHTML = t20;
   return k425(t20);
  }
 };
 ___set_2dhtml = t797;	// set! set-html
 var t799 = function (k426) {	// spock-elements
  loop: while(true) {
   var t801 = document.body.querySelectorAll("*[spock]");
   var t800 = Array.prototype.slice.call(t801);
   return k426(t800);
  }
 };
 ___spock_2delements = t799;	// set! spock-elements
 var t803 = function (k427, t21, t22, t23) {	// add-event-listener
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t804 = t22.addEventListener(t21, t23);
   return k427(t804);
  }
 };
 ___add_2devent_2dlistener = t803;	// set! add-event-listener
 var t806 = function (k428, t24, t25, t26) {	// set-event
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t25.event = t26;
   return k428(t25);
  }
 };
 ___set_2devent = t806;	// set! set-event
 var t808 = function (k429, t27, t28) {	// set-click
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t27.onclick = t28;
   return k429(t27);
  }
 };
 ___set_2dclick = t808;	// set! set-click
 var t810 = function (k430, t29, t30) {	// set-change
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t29.onchange = t30;
   return k430(t29);
  }
 };
 ___set_2dchange = t810;	// set! set-change
 var t812 = function (k431, t31, t32) {	// set-input
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t31.oninput = t32;
   return k431(t31);
  }
 };
 ___set_2dinput = t812;	// set! set-input
 var t814 = function (k432, t33, t34) {	// old-set-click
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t33.onclick = t34;
   return k432(t33);
  }
 };
 ___old_2dset_2dclick = t814;	// set! old-set-click
 var t816 = function (k433, t35) {	// slice
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t817 = Array.prototype.slice.call(t35);
   return k433(t817);
  }
 };
 ___slice = t816;	// set! slice
 var t819 = function (k434, t36) {	// children
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t820 = t36.childNodes;
  return ___slice(k434, t820);
 };
 ___children = t819;	// set! children
 var t822 = function (k435, t37) {	// car-safe
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t38 = t37;
   var t824 = (t38) instanceof SPOCK.Pair ;
   var t823;
   if(t824 !== false) {
    var t39 = t37;
    var t40 = t39;
    var t825 = t40.car;
    t823 = t825;
   }
   else {
    t823 = false;
   }
   return k435(t823);
  }
 };
 ___car_2dsafe = t822;	// set! car-safe
 var t827 = function (k436, t41) {	// cdr-safe
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t42 = t41;
   var t829 = (t42) instanceof SPOCK.Pair ;
   var t828;
   if(t829 !== false) {
    var t43 = t41;
    var t44 = t43;
    var t830 = t44.cdr;
    t828 = t830;
   }
   else {
    t828 = false;
   }
   return k436(t828);
  }
 };
 ___cdr_2dsafe = t827;	// set! cdr-safe
 var t832 = function (k437, t45) {	// empty?
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t47 = t45;
   var t834 = t47 === undefined;
   var t833;
   if(t834 !== false) {
    var t48 = t45;
    var t49 = t48;
    var t836 = null;
    var t50 = t836;
    var t837 = (t49) === (t50);
    var t835;
    if(t837 !== false) {
     var t51 = t45;
     var t838;
     if(t51 !== false) {
      t838 = false;
     }
     else {
      t838 = true;
     }
     t835 = t838;
    }
    else {
     t835 = false;
    }
    t833 = t835;
   }
   else {
    t833 = false;
   }
   var t46 = t833;
   var t839;
   if(t46 !== false) {
    t839 = false;
   }
   else {
    t839 = true;
   }
   return k437(t839);
  }
 };
 ___empty_3f = t832;	// set! empty?
 var t841 = function (k438, t52) {	// nodename
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t842 = t52.nodeName;
   return k438(t842);
  }
 };
 ___nodename = t841;	// set! nodename
 var t844 = function (k439, t53, t54, t55) {	// h
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t845 = function (t440) {	// t441
   var t56 = t440;
   var t846 = snabbdom.h(t53, t54, t56);
   return k439(t846);
  };
  var t441 = t845;
  var t848 = function (t442) {
   var t849;
   if(t442 !== false) {
    return ___list_2d_3evector(t441, t55);
   }
   else {
    var t58 = t55;
    var t852 = (t58) instanceof Array ;
    var t57 = t852;
    var t853;
    if(t57 !== false) {
     t853 = t57;
    }
    else {
     var t59 = t55;
     var t854 = typeof(t59);
     var t61 = t854;
     var t62 = "string";
     var t855 = (t61) === (t62);
     var t60 = t855;
     var t856;
     if(t60 !== false) {
      t856 = t60;
     }
     else {
      var t857 = (t59) instanceof SPOCK.String ;
      t856 = t857;
     }
     t853 = t856;
    }
    var t851;
    if(t853 !== false) {
     t851 = t55;
    }
    else {
     t851 = false;
    }
    return t441(t851);
   }
  };
  return ___list_3f(t848, t55);
 };
 ___h = t844;	// set! h
 var t860 = function (k443, t63, t64) {	// patch
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t861 = patch(t63, t64);
   return k443(t861);
  }
 };
 ___patch = t860;	// set! patch
 var t863 = function (k444, t65) {	// ajax-cb
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t864 = function(k865, x) { return k865(x.responseText); }
  var t866 = function (t445) {
   return ___log(k444, t445);
  };
  return t864(t866, t65);
 };
 ___ajax_2dcb = t863;	// set! ajax-cb
 var t869 = function (k446, t66, t67, t68) {	// ajax
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t870 = new XMLHttpRequest();
  var t69 = t870;
  var t871 = function (t447) {
   var t872 = t69.open(t66, t67, true);
   var t70 = t68;
   var t873 = SPOCK.callback(t70);
   t69.onreadystatechange = t873;
   var t874 = t69.send();
   return k446(t874);
  };
  return ___log(t871, t69);
 };
 ___ajax = t869;	// set! ajax
 var t877 = function (k448, t71) {	// get-callback
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t878 = function (t449) {	// t450
   var t72 = t449;
   var t879 = SPOCK.intern("callback");
   return ___get(k448, t72, t879);
  };
  var t450 = t878;
  var t73 = t71;
  var t882 = typeof(t73);
  var t75 = t882;
  var t76 = "string";
  var t883 = (t75) === (t76);
  var t74 = t883;
  var t884;
  if(t74 !== false) {
   t884 = t74;
  }
  else {
   var t885 = (t73) instanceof SPOCK.String ;
   t884 = t885;
  }
  var t881;
  if(t884 !== false) {
   return ___string_2d_3esymbol(t450, t71);
  }
  else {
   return t450(t71);
  }
 };
 ___get_2dcallback = t877;	// set! get-callback
 var t888 = function (k451) {	// waiting
  loop: while(true) {
   return k451(false);
  }
 };
 ___waiting = t888;	// set! waiting
 ___call_2fcc = ___call_2dwith_2dcurrent_2dcontinuation;	// set! call/cc
 var t890 = null;
 ____2aqueue_2a = t890;	// set! *queue*
 var t891 = function (k452, t77) {	// *enqueue*
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t892 = function (t455) {
   var t78 = t455;
   var t454 = t78;
   var t893 = function (t453) {
    ____2aqueue_2a = t453;	// set! *queue*
    return k452(undefined);
   };
   return ___append(t893, ____2aqueue_2a, t454);
  };
  return ____25list(t892, t77);
 };
 ____2aenqueue_2a = t891;	// set! *enqueue*
 var t897 = function (k456) {	// *dequeue*
  loop: while(true) {
   var t80 = ____2aqueue_2a;
   var t81 = t80;
   var t898 = t81.car;
   var t79 = t898;
   var t82 = ____2aqueue_2a;
   var t83 = t82;
   var t899 = t83.cdr;
   ____2aqueue_2a = t899;	// set! *queue*
   return k456(t79);
  }
 };
 ____2adequeue_2a = t897;	// set! *dequeue*
 var t901 = function (k457) {	// yield
  var t84 = ____2aqueue_2a;
  var t85 = t84;
  var t903 = null;
  var t86 = t903;
  var t904 = (t85) === (t86);
  var t902;
  if(t904 !== false) {
   return ___waiting(k457);
  }
  else {
   var t906 = function (t458) {
    var t87 = t458;
    var t907 = function (t459) {
     var t908 = function (t460) {
      return t460(k457);
     };
     return t87(t908);
    };
    return ___print(t907, "YIELDING");
   };
   return ____2adequeue_2a(t906);
  }
 };
 ___yield = t901;	// set! yield
 var t913 = function (k461, t88, t89) {	// assoc-val
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t914 = function (t462) {
   return ___cdr_2dsafe(k461, t462);
  };
  return ___assoc(t914, t88, t89);
 };
 ___assoc_2dval = t913;	// set! assoc-val
 ___merge_2dbindings = ___append;	// set! merge-bindings
 var t917 = function (k463, t90, t91, t92) {	// put-cons!
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t93 = t92;
  var t918 = function (t466) {
   var t95 = t466;
   var t919;
   if(t95 !== false) {
    t919 = t95;
   }
   else {
    var t920 = null;
    t919 = t920;
   }
   var t465 = t919;
   var t94 = t465;
   var t921 = new SPOCK.Pair(t93, t94);
   var t464 = t921;
   return ___put_21(k463, t90, t91, t464);
  };
  return ___get(t918, t90, t91);
 };
 ___put_2dcons_21 = t917;	// set! put-cons!
 var t924 = function (k467, t96, t97) {	// get-binding
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t925 = function (t468) {
   var t98 = t468;
   var t926;
   if(t98 !== false) {
    var t99 = t98;
    var t100 = t99;
    var t927 = t100.cdr;
    t926 = t927;
   }
   else {
    t926 = false;
   }
   return k467(t926);
  };
  return ___assoc(t925, t96, t97);
 };
 ___get_2dbinding = t924;	// set! get-binding
 var t930 = function (k469, t101, t102) {	// send-bindings
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t931 = function (t470) {
   return t470(k469, t102);
  };
  var t933 = SPOCK.intern("continuations");
  return ___get(t931, t101, t933);
 };
 ___send_2dbindings = t930;	// set! send-bindings
 var t935 = function (k471, t103, t104) {	// three-way-split
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t105 = undefined;
  var t936 = function (k472, t106, t107, t108, t109, t110) {	// t105
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t111 = t107;
   var t112 = t111;
   var t938 = null;
   var t113 = t938;
   var t939 = (t112) === (t113);
   var t937;
   if(t939 !== false) {
    var t940 = function (t474) {
     var t941 = function (t473) {
      var t114 = t473;
      return k472(t114);
     };
     return ____25list(t941, t474, t109, t110);
    };
    return ___append(t940, t106, t108);
   }
   else {
    var t116 = t107;
    var t117 = t116;
    var t945 = t117.car;
    var t115 = t945;
    var t118 = undefined;
    var t946 = function (k475, t119, t120) {	// t118
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t121 = t119;
     var t122 = t121;
     var t948 = null;
     var t123 = t948;
     var t949 = (t122) === (t123);
     var t947;
     if(t949 !== false) {
      var t124 = t107;
      var t125 = t124;
      var t950 = t125.cdr;
      var t126 = t115;
      var t127 = t110;
      var t951 = new SPOCK.Pair(t126, t127);
      return t105(k475, t120, t950, t108, t109, t951);
     }
     else {
      var t129 = t119;
      var t130 = t129;
      var t953 = t130.car;
      var t128 = t953;
      var t131 = t115;
      var t132 = t128;
      var t955 = SPOCK.equalp(t131, t132);
      var t954;
      if(t955 !== false) {
       var t956 = function (t476) {
        var t135 = t107;
        var t136 = t135;
        var t957 = t136.cdr;
        var t137 = t115;
        var t138 = t109;
        var t958 = new SPOCK.Pair(t137, t138);
        return t105(k475, t476, t957, t108, t958, t110);
       };
       var t133 = t119;
       var t134 = t133;
       var t960 = t134.cdr;
       return ___append(t956, t120, t960);
      }
      else {
       var t139 = t119;
       var t140 = t139;
       var t962 = t140.cdr;
       var t141 = t128;
       var t142 = t120;
       var t963 = new SPOCK.Pair(t141, t142);
       return t118(k475, t962, t963);
      }
      t947 = t954;
     }
    };
    t118 = t946;	// set! t118
    var t965 = null;
    return t118(k472, t106, t965);
   }
  };
  t105 = t936;	// set! t105
  var t967 = null;
  var t968 = null;
  var t969 = null;
  return t105(k471, t103, t104, t967, t968, t969);
 };
 ___three_2dway_2dsplit = t935;	// set! three-way-split
 var t971 = function (k477, t143, t144) {	// merge-alist-sets
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t146 = t144;
  var t147 = t146;
  var t972 = t147.car;
  var t145 = t972;
  var t148 = undefined;
  var t973 = function (k478, t149, t150, t151) {	// t148
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t153 = t150;
   var t154 = t153;
   var t975 = null;
   var t155 = t975;
   var t976 = (t154) === (t155);
   var t152 = t976;
   var t977;
   if(t152 !== false) {
    t977 = t152;
   }
   else {
    var t156 = t149;
    var t157 = t156;
    var t978 = null;
    var t158 = t978;
    var t979 = (t157) === (t158);
    t977 = t979;
   }
   var t974;
   if(t977 !== false) {
    var t980 = function (t481) {
     var t163 = t481;
     var t480 = t163;
     var t161 = t480;
     var t162 = t150;
     var t981 = new SPOCK.Pair(t161, t162);
     var t479 = t981;
     var t159 = t479;
     var t160 = t151;
     var t982 = new SPOCK.Pair(t159, t160);
     return k478(t982);
    };
    return ____25list(t980, t145);
   }
   else {
    var t165 = t149;
    var t167 = t165;
    var t168 = t167;
    var t985 = t168.car;
    var t166 = t985;
    var t169 = t166;
    var t986 = t169.car;
    var t164 = t986;
    var t171 = t149;
    var t173 = t171;
    var t174 = t173;
    var t987 = t174.car;
    var t172 = t987;
    var t175 = t172;
    var t988 = t175.cdr;
    var t170 = t988;
    var t989 = function (t482) {
     var t176 = t482;
     var t178 = t176;
     var t179 = t178;
     var t990 = t179.car;
     var t177 = t990;
     var t181 = t176;
     var t183 = t181;
     var t184 = t183;
     var t991 = t184.cdr;
     var t182 = t991;
     var t185 = t182;
     var t992 = t185.car;
     var t180 = t992;
     var t993 = function (t483) {
      var t186 = t483;
      var t994 = function (t486) {
       var t189 = t486;
       var t485 = t189;
       var t995 = function (t484) {
        var t187 = t149;
        var t188 = t187;
        var t996 = t188.cdr;
        return t148(k478, t996, t186, t484);
       };
       return ___append(t995, t485, t151);
      };
      var t190 = t164;
      var t191 = t177;
      var t999 = new SPOCK.Pair(t190, t191);
      var t194 = t145;
      var t195 = t164;
      var t1000 = new SPOCK.Pair(t194, t195);
      var t192 = t1000;
      var t193 = t180;
      var t1001 = new SPOCK.Pair(t192, t193);
      return ____25list(t994, t999, t1001);
     };
     return ___caddr(t993, t176);
    };
    return ___three_2dway_2dsplit(t989, t170, t150);
   }
  };
  t148 = t973;	// set! t148
  var t196 = t144;
  var t197 = t196;
  var t1005 = t197.cdr;
  var t1006 = null;
  return t148(k477, t143, t1005, t1006);
 };
 ___merge_2dalist_2dsets = t971;	// set! merge-alist-sets
 var t1008 = function (k487, t198) {	// merge-continuation-lists
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t199 = undefined;
  var t1009 = function (k488, t200, t201) {	// t199
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t202 = t201;
   var t203 = t202;
   var t1011 = null;
   var t204 = t1011;
   var t1012 = (t203) === (t204);
   var t1010;
   if(t1012 !== false) {
    return k488(t200);
   }
   else {
    var t1014 = function (t489) {
     var t207 = t201;
     var t208 = t207;
     var t1015 = t208.cdr;
     return t199(k488, t489, t1015);
    };
    var t205 = t201;
    var t206 = t205;
    var t1017 = t206.car;
    return ___merge_2dalist_2dsets(t1014, t200, t1017);
   }
  };
  t199 = t1009;	// set! t199
  var t1019 = null;
  return t199(k487, t1019, t198);
 };
 ___merge_2dcontinuation_2dlists = t1008;	// set! merge-continuation-lists
 var t1021 = function (k490, t209) {	// send-vars
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1022 = function (t497) {
   var t1023 = function (t496) {
    var t1024 = function (t491) {
     return ___yield(k490);
    };
    var t1026 = function (k492, t210) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1027 = function (t493) {
      var t213 = t210;
      var t214 = t213;
      var t1028 = t214.car;
      var t211 = t1028;
      var t215 = t210;
      var t216 = t215;
      var t1029 = t216.cdr;
      var t212 = t1029;
      var t218 = t212;
      var t219 = t218;
      var t1031 = null;
      var t220 = t1031;
      var t1032 = (t219) === (t220);
      var t217 = t1032;
      var t1033;
      if(t217 !== false) {
       t1033 = false;
      }
      else {
       t1033 = true;
      }
      var t1030;
      if(t1033 !== false) {
       var t1034 = function (k494, t221) {
        var r = SPOCK.count(arguments);
        if(r) return r;
        var t1035 = function (k495) {
         return t221(k495, t209);
        };
        return ____2aenqueue_2a(k494, t1035);
       };
       return ___map(k492, t1034, t212);
      }
      else {
       return k492(undefined);
      }
     };
     return ___print(t1027, "CONTINUATIONS: ", t210);
    };
    return ___map(t1024, t1026, t496);
   };
   return ___merge_2dcontinuation_2dlists(t1023, t497);
  };
  var t1043 = function (k498, t222) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t224 = t222;
   var t225 = t224;
   var t1044 = t225.car;
   var t223 = t1044;
   var t226 = t223;
   var t1045 = function (t499) {
    var t227 = t499;
    var t1046 = new SPOCK.Pair(t226, t227);
    return k498(t1046);
   };
   var t1048 = SPOCK.intern("continuations");
   return ___get(t1045, t223, t1048);
  };
  return ___map(t1022, t1043, t209);
 };
 ___send_2dvars = t1021;	// set! send-vars
 var t1051 = function (k500, t228, t229) {	// register-component
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1052 = function (t501) {	// t502
   var t230 = t501;
   var t1053 = SPOCK.intern("callback");
   return ___put_21(k500, t230, t1053, t229);
  };
  var t502 = t1052;
  var t231 = t228;
  var t1056 = typeof(t231);
  var t233 = t1056;
  var t234 = "string";
  var t1057 = (t233) === (t234);
  var t232 = t1057;
  var t1058;
  if(t232 !== false) {
   t1058 = t232;
  }
  else {
   var t1059 = (t231) instanceof SPOCK.String ;
   t1058 = t1059;
  }
  var t1055;
  if(t1058 !== false) {
   return ___string_2d_3esymbol(t502, t228);
  }
  else {
   return t502(t228);
  }
 };
 ___register_2dcomponent = t1051;	// set! register-component
 var t1062 = function (k503, t235) {	// click1
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t236 = undefined;
  var t1063 = function (t507) {
   t236 = t507;	// set! t236
   var t504 = undefined;
   var t1064 = function (t505) {
    return ___yield(k503);
   };
   var t1066 = function (k506, t243) {	// t242
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t1067 = new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("status"), "loaded."), new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("class"), "blue"), null));
    var t244 = t1067;
    return ___send_2dvars(k506, t244);
   };
   var t242 = t1066;
   var t1069 = SPOCK.callback(t242);
   return ___set_2dclick(t1064, t235, t1069);
  };
  var t1071 = function (k508, t237) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1072 = function (t515) {
    var t240 = t515;
    var t514 = t240;
    var t1073 = function (t509) {
     var t1074 = function (t510) {
      var t241 = t510;
      return k508(t241);
     };
     return ____25list(t1074);
    };
    var t1077 = function (k511, t238) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1078 = SPOCK.intern("continuations");
     var t1079 = function (k512, t239) {
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t1080 = function (t513) {
       return t237(k512, t513);
      };
      return ___append(t1080, t239, t236);
     };
     return ___put_2dcons_21(k511, t238, t1078, t1079);
    };
    return ___map(t1073, t1077, t514);
   };
   return ____25list(t1072);
  };
  return ___call_2fcc(t1063, t1071);
 };
 ___click1 = t1062;	// set! click1
 return ___register_2dcomponent(k410, "click1", ___click1);
};
SPOCK.run(t752);
var t1088 = function (k516) {
 var t1089 = function (k517, t245) {	// click2
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t246 = undefined;
  var t1090 = function (t522) {
   t246 = t522;	// set! t246
   var t518 = undefined;
   var t1091 = function (t520) {
    var t252 = t520;
    var t1092 = function (t519) {
     return ___yield(k517);
    };
    var t1094 = function (k521, t254) {	// t253
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1095 = new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("class"), "green"), null);
     var t255 = t1095;
     return ___send_2dvars(k521, t255);
    };
    var t253 = t1094;
    var t1097 = SPOCK.callback(t253);
    return ___set_2dclick(t1092, t245, t1097);
   };
   var t1099 = SPOCK.intern("count");
   return ___assoc_2dval(t1091, t1099, t246);
  };
  var t1101 = function (k523, t247) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1102 = function (t531) {
    var t250 = t531;
    var t530 = t250;
    var t1103 = function (t524) {
     var t1104 = function (t526) {
      var t1105 = function (t525) {
       var t251 = t525;
       return k523(t251);
      };
      return ____25list(t1105, t526);
     };
     var t1108 = SPOCK.intern("count");
     return ___assoc(t1104, t1108, ____2ainits_2a);
    };
    var t1110 = function (k527, t248) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1111 = SPOCK.intern("continuations");
     var t1112 = function (k528, t249) {
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t1113 = function (t529) {
       return t247(k528, t529);
      };
      return ___append(t1113, t249, t246);
     };
     return ___put_2dcons_21(k527, t248, t1111, t1112);
    };
    return ___map(t1103, t1110, t530);
   };
   var t1118 = SPOCK.intern("count");
   return ____25list(t1102, t1118);
  };
  return ___call_2fcc(t1090, t1101);
 };
 ___click2 = t1089;	// set! click2
 var t1121 = function (k532, t256) {
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t257 = undefined;
  var t1122 = function (t542) {
   t257 = t542;	// set! t257
   var t533 = undefined;
   var t1123 = function (t535) {
    var t263 = t535;
    var t1124 = function (k536, t265) {	// t264
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1125 = function (t537) {
      var t1126 = function (k538) {
       var t266 = t263;
       var t267 = 1;
       var t1127 = (t266)  +  (t267);
       return ___values(k538, t263, t1127);
      };
      var t1129 = function (k539, t268, t269) {
       var r = SPOCK.count(arguments);
       if(r) return r;
       var t1130 = function (t541) {
        var t270 = t541;
        var t540 = t270;
        return ___send_2dvars(k539, t540);
       };
       var t1132 = SPOCK.intern("selected");
       var t271 = t1132;
       var t272 = t268;
       var t1133 = new SPOCK.Pair(t271, t272);
       var t1134 = SPOCK.intern("count");
       var t273 = t1134;
       var t274 = t269;
       var t1135 = new SPOCK.Pair(t273, t274);
       return ____25list(t1130, t1133, t1135);
      };
      return ___call_2dwith_2dvalues(k536, t1126, t1129);
     };
     return ___log(t1125, t263);
    };
    var t264 = t1124;
    var t1139 = SPOCK.callback(t264);
    t256.onclick = t1139;
    var t534 = t256;
    return ___yield(k532);
   };
   var t1141 = SPOCK.intern("count");
   return ___assoc_2dval(t1123, t1141, t257);
  };
  var t1143 = function (k543, t258) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1144 = function (t551) {
    var t261 = t551;
    var t550 = t261;
    var t1145 = function (t544) {
     var t1146 = function (t546) {
      var t1147 = function (t545) {
       var t262 = t545;
       return k543(t262);
      };
      return ____25list(t1147, t546);
     };
     var t1150 = SPOCK.intern("count");
     return ___assoc(t1146, t1150, ____2ainits_2a);
    };
    var t1152 = function (k547, t259) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1153 = SPOCK.intern("continuations");
     var t1154 = function (k548, t260) {
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t1155 = function (t549) {
       return t258(k548, t549);
      };
      return ___append(t1155, t260, t257);
     };
     return ___put_2dcons_21(k547, t259, t1153, t1154);
    };
    return ___map(t1145, t1152, t550);
   };
   var t1160 = SPOCK.intern("count");
   return ____25list(t1144, t1160);
  };
  return ___call_2fcc(t1122, t1143);
 };
 return ___register_2dcomponent(k516, "click3", t1121);
};
SPOCK.run(t1088);
var t1164 = function (k552) {
 var t1165 = function (k553, t275, t276) {	// range
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t277 = t275;
  var t278 = t276;
  var t1167 = SPOCK.equalp(t277, t278);
  var t1166;
  if(t1167 !== false) {
   var t1168 = null;
   return k553(t1168);
  }
  else {
   var t279 = t275;
   var t1170 = function (t554) {
    var t280 = t554;
    var t1171 = new SPOCK.Pair(t279, t280);
    return k553(t1171);
   };
   var t281 = 1;
   var t282 = t275;
   var t1173 = (t281)  +  (t282);
   return ___range(t1170, t1173, t276);
  }
 };
 ___range = t1165;	// set! range
 var t1175 = function (k555, t283) {	// click0
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t284 = undefined;
  var t1176 = function (t563) {
   t284 = t563;	// set! t284
   var t556 = undefined;
   var t1177 = function (t558) {
    var t290 = t558;
    var t1178 = function (t557) {
     return ___yield(k555);
    };
    var t1180 = function (k559, t292) {	// t291
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1181 = SPOCK.intern("messages");
     var t296 = t1181;
     var t1182 = function (t562) {
      var t297 = t562;
      var t1183 = new SPOCK.Pair(t296, t297);
      var t561 = t1183;
      var t294 = t561;
      var t1184 = new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("class"), "green"), null);
      var t295 = t1184;
      var t1185 = new SPOCK.Pair(t294, t295);
      var t560 = t1185;
      var t293 = t560;
      return ___send_2dvars(k559, t293);
     };
     return ___range(t1182, 0, t290);
    };
    var t291 = t1180;
    var t1188 = SPOCK.callback(t291);
    return ___set_2dclick(t1178, t283, t1188);
   };
   var t1190 = SPOCK.intern("count");
   return ___assoc_2dval(t1177, t1190, t284);
  };
  var t1192 = function (k564, t285) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1193 = function (t572) {
    var t288 = t572;
    var t571 = t288;
    var t1194 = function (t565) {
     var t1195 = function (t567) {
      var t1196 = function (t566) {
       var t289 = t566;
       return k564(t289);
      };
      return ____25list(t1196, t567);
     };
     var t1199 = SPOCK.intern("count");
     return ___assoc(t1195, t1199, ____2ainits_2a);
    };
    var t1201 = function (k568, t286) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1202 = SPOCK.intern("continuations");
     var t1203 = function (k569, t287) {
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t1204 = function (t570) {
       return t285(k569, t570);
      };
      return ___append(t1204, t287, t284);
     };
     return ___put_2dcons_21(k568, t286, t1202, t1203);
    };
    return ___map(t1194, t1201, t571);
   };
   var t1209 = SPOCK.intern("count");
   return ____25list(t1193, t1209);
  };
  return ___call_2fcc(t1176, t1192);
 };
 ___click0 = t1175;	// set! click0
 return ___register_2dcomponent(k552, "click0", ___click0);
};
SPOCK.run(t1164);
var t1213 = function (k573) {
 var t1214 = function (k574, t298) {	// changeme
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t299 = undefined;
  var t1215 = function (t580) {
   t299 = t580;	// set! t299
   var t575 = undefined;
   var t1216 = function (t576) {
    return ___yield(k574);
   };
   var t1218 = function (k577, t306) {	// t305
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t308 = t306;
    var t1219 = function (t579) {
     var t309 = t579;
     var t578 = t309;
     var t307 = t578;
     return ___send_2dvars(k577, t307);
    };
    var t1221 = SPOCK.intern("status");
    var t310 = t1221;
    var t1223 = t308.target;
    var t1222 = t1223.value;
    var t311 = t1222;
    var t1224 = new SPOCK.Pair(t310, t311);
    return ____25list(t1219, t1224);
   };
   var t305 = t1218;
   var t1226 = SPOCK.callback(t305);
   return ___set_2dchange(t1216, t298, t1226);
  };
  var t1228 = function (k581, t300) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1229 = function (t588) {
    var t303 = t588;
    var t587 = t303;
    var t1230 = function (t582) {
     var t1231 = function (t583) {
      var t304 = t583;
      return k581(t304);
     };
     return ____25list(t1231);
    };
    var t1234 = function (k584, t301) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1235 = SPOCK.intern("continuations");
     var t1236 = function (k585, t302) {
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t1237 = function (t586) {
       return t300(k585, t586);
      };
      return ___append(t1237, t302, t299);
     };
     return ___put_2dcons_21(k584, t301, t1235, t1236);
    };
    return ___map(t1230, t1234, t587);
   };
   return ____25list(t1229);
  };
  return ___call_2fcc(t1215, t1228);
 };
 ___changeme = t1214;	// set! changeme
 return ___register_2dcomponent(k573, "changeme", ___changeme);
};
SPOCK.run(t1213);
var t1245 = function (k589) {
 var t1246 = function (k590, t312) {	// single-render
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t313 = t312;
  var t314 = undefined;
  var t1247 = function (t603) {
   t314 = t603;	// set! t314
   var t591 = undefined;
   var t1248 = function (t593) {
    var t320 = t593;
    var t1249 = function (t596) {
     var t1250 = function (t598) {
      var t1251 = function (t602) {
       var t1252 = function (t600) {
        var t1253 = function (t601) {
         var t1254 = function (t599) {
          var t1255 = function (t597) {
           var t1256 = function (t594) {
            var t321 = t594;
            var t1257 = function (t595) {
             t313 = t595;	// set! t313
             var t592 = undefined;
             return ___yield(k590);
            };
            return ___patch(t1257, t313, t321);
           };
           return ___h(t1256, t596, false, t597);
          };
          return ___vector(t1255, t598, t599);
         };
         return ___h(t1254, "b", t600, t601);
        };
        return ___vector(t1253, t320, t320);
       };
       return ____25(t1252, "attrs", t602);
      };
      return ____25(t1251, "class", "green");
     };
     return ___h(t1250, "i", false, "Status: ");
    };
    return ___nodename(t1249, t312);
   };
   var t1268 = SPOCK.intern("status");
   return ___assoc_2dval(t1248, t1268, t314);
  };
  var t1270 = function (k604, t315) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1271 = function (t612) {
    var t318 = t612;
    var t611 = t318;
    var t1272 = function (t605) {
     var t1273 = function (t607) {
      var t1274 = function (t606) {
       var t319 = t606;
       return k604(t319);
      };
      return ____25list(t1274, t607);
     };
     var t1277 = SPOCK.intern("status");
     return ___assoc(t1273, t1277, ____2ainits_2a);
    };
    var t1279 = function (k608, t316) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1280 = SPOCK.intern("continuations");
     var t1281 = function (k609, t317) {
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t1282 = function (t610) {
       return t315(k609, t610);
      };
      return ___append(t1282, t317, t314);
     };
     return ___put_2dcons_21(k608, t316, t1280, t1281);
    };
    return ___map(t1272, t1279, t611);
   };
   var t1287 = SPOCK.intern("status");
   return ____25list(t1271, t1287);
  };
  return ___call_2fcc(t1247, t1270);
 };
 ___single_2drender = t1246;	// set! single-render
 return ___register_2dcomponent(k589, "single-render", ___single_2drender);
};
SPOCK.run(t1245);
var t1291 = function (k613) {
 var t1292 = function (k614, t322) {	// map-messages
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t323 = t322;
  var t324 = undefined;
  var t1293 = function (t652) {
   t324 = t652;	// set! t324
   var t615 = undefined;
   var t1294 = function (t617) {
    var t330 = t617;
    var t1295 = function (t618) {
     var t331 = t618;
     var t1296 = function (t619) {
      var t332 = t619;
      var t1297 = function (t620) {
       var t333 = t620;
       var t1298 = function (t621) {
        var t334 = t621;
        var t1299 = function (t624) {
         var t1300 = function (t626) {
          var t1301 = function (t625) {
           var t1302 = function (t622) {
            var t335 = t622;
            var t1303 = function (t623) {
             t323 = t623;	// set! t323
             var t616 = undefined;
             return ___yield(k614);
            };
            return ___patch(t1303, t323, t335);
           };
           return ___h(t1302, t624, false, t625);
          };
          return ___apply(t1301, ___append, t626);
         };
         var t1308 = function (k627, t336) {
          var r = SPOCK.count(arguments);
          if(r) return r;
          var t337 = t336;
          var t1309 = function (t646) {
           var t1310 = function (t630) {
            var t1311 = function (t632) {
             var t1312 = function (t633) {
              var t1313 = function (t645) {
               var t1314 = function (t643) {
                var t1315 = function (t644) {
                 var t1316 = function (t634) {
                  var t1317 = function (t642) {
                   var t1318 = function (t636) {
                    var t1319 = function (t640) {
                     var t1320 = function (t639) {
                      var t1321 = function (t638) {
                       var t1322 = function (t637) {
                        var t1323 = function (t635) {
                         var t1324 = function (t631) {
                          var t1325 = function (t629) {
                           var t1326 = function (t628) {
                            var t338 = t628;
                            return k627(t338);
                           };
                           return ____25list(t1326, t629);
                          };
                          return ___h(t1325, "div", t630, t631);
                         };
                         return ___vector(t1324, t632, t633, t634, t635);
                        };
                        return ___h(t1323, "div", t636, t637);
                       };
                       var t347 = t334;
                       var t1332;
                       if(t347 !== false) {
                        t1332 = t347;
                       }
                       else {
                        t1332 = "none";
                       }
                       return ___vector(t1322, t337, "/", t1332, t638);
                      };
                      return ___h(t1321, "button", t639, "click me");
                     };
                     return ____25(t1320, "on", t640);
                    };
                    var t1336 = function (k641, t349) {	// t348
                     var r = SPOCK.count(arguments);
                     if(r) return r;
                     return ___log(k641, t337);
                    };
                    var t348 = t1336;
                    var t1338 = SPOCK.callback(t348);
                    return ____25(t1319, "click", t1338);
                   };
                   return ____25(t1318, "class", t642);
                  };
                  var t345 = t337;
                  var t346 = t334;
                  var t1341 = SPOCK.equalp(t345, t346);
                  return ____25(t1317, "selected", t1341);
                 };
                 return ___h(t1316, "div", t643, t644);
                };
                return ___vector(t1315, " ducks: ", t331);
               };
               return ____25(t1314, "attrs", t645);
              };
              return ____25(t1313, "class", t332);
             };
             return ___h(t1312, "div", false, t337);
            };
            return ___h(t1311, "div", false, t333);
           };
           return ____25(t1310, "on", t646);
          };
          var t1350 = function (k647, t340) {	// t339
           var r = SPOCK.count(arguments);
           if(r) return r;
           var t1351 = function (k648) {
            loop: while(true) {
             return k648(t337);
            }
           };
           var t1353 = function (k649, t341) {
            var r = SPOCK.count(arguments);
            if(r) return r;
            var t1354 = function (t651) {
             var t342 = t651;
             var t650 = t342;
             return ___send_2dvars(k649, t650);
            };
            var t1356 = SPOCK.intern("selected");
            var t343 = t1356;
            var t344 = t341;
            var t1357 = new SPOCK.Pair(t343, t344);
            return ____25list(t1354, t1357);
           };
           return ___call_2dwith_2dvalues(k647, t1351, t1353);
          };
          var t339 = t1350;
          var t1360 = SPOCK.callback(t339);
          return ____25(t1309, "mouseover", t1360);
         };
         return ___map(t1300, t1308, t330);
        };
        return ___nodename(t1299, t322);
       };
       var t1364 = SPOCK.intern("selected");
       return ___assoc_2dval(t1298, t1364, t324);
      };
      var t1366 = SPOCK.intern("status");
      return ___assoc_2dval(t1297, t1366, t324);
     };
     var t1368 = SPOCK.intern("class");
     return ___assoc_2dval(t1296, t1368, t324);
    };
    var t1370 = SPOCK.intern("count");
    return ___assoc_2dval(t1295, t1370, t324);
   };
   var t1372 = SPOCK.intern("messages");
   return ___assoc_2dval(t1294, t1372, t324);
  };
  var t1374 = function (k653, t325) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1375 = function (t665) {
    var t328 = t665;
    var t664 = t328;
    var t1376 = function (t654) {
     var t1377 = function (t656) {
      var t1378 = function (t657) {
       var t1379 = function (t658) {
        var t1380 = function (t659) {
         var t1381 = function (t660) {
          var t1382 = function (t655) {
           var t329 = t655;
           return k653(t329);
          };
          return ____25list(t1382, t656, t657, t658, t659, t660);
         };
         var t1385 = SPOCK.intern("selected");
         return ___assoc(t1381, t1385, ____2ainits_2a);
        };
        var t1387 = SPOCK.intern("status");
        return ___assoc(t1380, t1387, ____2ainits_2a);
       };
       var t1389 = SPOCK.intern("class");
       return ___assoc(t1379, t1389, ____2ainits_2a);
      };
      var t1391 = SPOCK.intern("count");
      return ___assoc(t1378, t1391, ____2ainits_2a);
     };
     var t1393 = SPOCK.intern("messages");
     return ___assoc(t1377, t1393, ____2ainits_2a);
    };
    var t1395 = function (k661, t326) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1396 = SPOCK.intern("continuations");
     var t1397 = function (k662, t327) {
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t1398 = function (t663) {
       return t325(k662, t663);
      };
      return ___append(t1398, t327, t324);
     };
     return ___put_2dcons_21(k661, t326, t1396, t1397);
    };
    return ___map(t1376, t1395, t664);
   };
   var t1403 = SPOCK.intern("messages");
   var t1404 = SPOCK.intern("count");
   var t1405 = SPOCK.intern("class");
   var t1406 = SPOCK.intern("status");
   var t1407 = SPOCK.intern("selected");
   return ____25list(t1375, t1403, t1404, t1405, t1406, t1407);
  };
  return ___call_2fcc(t1293, t1374);
 };
 ___map_2dmessages = t1292;	// set! map-messages
 var t1410 = function (k666, t350) {	// map-table
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t351 = t350;
  var t352 = undefined;
  var t1411 = function (t690) {
   t352 = t690;	// set! t352
   var t667 = undefined;
   var t1412 = function (t669) {
    var t358 = t669;
    var t1413 = function (t672) {
     var t1414 = function (t689) {
      var t1415 = function (t675) {
       var t1416 = function (t674) {
        var t1417 = function (t673) {
         var t1418 = function (t670) {
          var t359 = t670;
          var t1419 = function (t671) {
           t351 = t671;	// set! t351
           var t668 = undefined;
           return ___yield(k666);
          };
          return ___patch(t1419, t351, t359);
         };
         return ___h(t1418, t672, false, t673);
        };
        return ___vector(t1417, t674);
       };
       return ___h(t1416, "div", false, t675);
      };
      var t1425 = function (k676, t360) {
       var r = SPOCK.count(arguments);
       if(r) return r;
       var t1426 = function (t688) {
        var t1427 = function (t677) {
         return ___h(k676, "div", false, t677);
        };
        var t1429 = function (k678, t361) {
         var r = SPOCK.count(arguments);
         if(r) return r;
         var t1430 = function (t681) {
          var t1431 = function (t682) {
           var t1432 = function (t679) {
            var t1433 = function (t680) {
             return ___h(k678, "div", t679, t680);
            };
            return ___vector(t1433, t360, ", ", t361);
           };
           return ____25(t1432, "class", t681, "on", t682);
          };
          var t1437 = function (k683, t367) {	// t366
           var r = SPOCK.count(arguments);
           if(r) return r;
           var t1438 = function (k684) {
            loop: while(true) {
             var t368 = t360;
             var t369 = t361;
             var t1439 = (t368)  +  (t369);
             return k684(t1439);
            }
           };
           var t1441 = function (k685, t370) {
            var r = SPOCK.count(arguments);
            if(r) return r;
            var t1442 = function (t687) {
             var t371 = t687;
             var t686 = t371;
             return ___send_2dvars(k685, t686);
            };
            var t1444 = SPOCK.intern("selected-square");
            var t372 = t1444;
            var t373 = t370;
            var t1445 = new SPOCK.Pair(t372, t373);
            return ____25list(t1442, t1445);
           };
           return ___call_2dwith_2dvalues(k683, t1438, t1441);
          };
          var t366 = t1437;
          var t1448 = SPOCK.callback(t366);
          return ____25(t1431, "mouseover", t1448);
         };
         var t364 = t360;
         var t365 = t361;
         var t1450 = (t364)  +  (t365);
         var t362 = t1450;
         var t363 = t358;
         var t1451 = SPOCK.equalp(t362, t363);
         return ____25(t1430, "cell", true, "selected", t1451);
        };
        return ___map(t1427, t1429, t688);
       };
       return ___range(t1426, 0, 20);
      };
      return ___map(t1415, t1425, t689);
     };
     return ___range(t1414, 0, 20);
    };
    return ___nodename(t1413, t350);
   };
   var t1458 = SPOCK.intern("selected");
   return ___assoc_2dval(t1412, t1458, t352);
  };
  var t1460 = function (k691, t353) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1461 = function (t699) {
    var t356 = t699;
    var t698 = t356;
    var t1462 = function (t692) {
     var t1463 = function (t694) {
      var t1464 = function (t693) {
       var t357 = t693;
       return k691(t357);
      };
      return ____25list(t1464, t694);
     };
     var t1467 = SPOCK.intern("selected");
     return ___assoc(t1463, t1467, ____2ainits_2a);
    };
    var t1469 = function (k695, t354) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1470 = SPOCK.intern("continuations");
     var t1471 = function (k696, t355) {
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t1472 = function (t697) {
       return t353(k696, t697);
      };
      return ___append(t1472, t355, t352);
     };
     return ___put_2dcons_21(k695, t354, t1470, t1471);
    };
    return ___map(t1462, t1469, t698);
   };
   var t1477 = SPOCK.intern("selected");
   return ____25list(t1461, t1477);
  };
  return ___call_2fcc(t1411, t1460);
 };
 ___map_2dtable = t1410;	// set! map-table
 return ___register_2dcomponent(k613, "map-messages", ___map_2dtable);
};
SPOCK.run(t1291);
var t1481 = function (k700) {
 var t1482 = new SPOCK.Pair(SPOCK.intern("status"), "initialized");
 var t374 = t1482;
 var t1483 = SPOCK.intern("messages");
 var t378 = t1483;
 var t1484 = function (t704) {
  var t379 = t704;
  var t1485 = new SPOCK.Pair(t378, t379);
  var t703 = t1485;
  var t376 = t703;
  var t1486 = new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("count"), 4), new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("class"), "blue"), new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("selected"), false), null)));
  var t377 = t1486;
  var t1487 = new SPOCK.Pair(t376, t377);
  var t702 = t1487;
  var t375 = t702;
  var t1488 = new SPOCK.Pair(t374, t375);
  var t701 = t1488;
  ____2ainits_2a = t701;	// set! *inits*
  return k700(undefined);
 };
 return ___range(t1484, 0, 800);
};
SPOCK.run(t1481);
var t1491 = function (k705) {
 var t1492 = function (t708) {
  var t1493 = function (k706, t380) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1494 = t380.getAttribute("spock");
   var t381 = t1494;
   var t1495 = function (t707) {
    return t707(k706, t380);
   };
   return ___get_2dcallback(t1495, t381);
  };
  return ___map(k705, t1493, t708);
 };
 return ___spock_2delements(t1492);
};
SPOCK.run(t1491);
var t1500 = function (k709) {
 var t382 = undefined;
 var t1501 = function (t717) {
  t382 = t717;	// set! t382
  var t710 = undefined;
  var t1502 = function (t712) {
   var t388 = t712;
   var t1503 = function (t711) {
    return ___yield(k709);
   };
   var t1505 = function (k713) {
    loop: while(true) {
     var t389 = t388;
     var t390 = 1;
     var t1506 = (t389)  +  (t390);
     return k713(t1506);
    }
   };
   var t1508 = function (k714, t391) {
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t1509 = function (t716) {
     var t392 = t716;
     var t715 = t392;
     return ___send_2dvars(k714, t715);
    };
    var t1511 = SPOCK.intern("selected");
    var t393 = t1511;
    var t394 = t391;
    var t1512 = new SPOCK.Pair(t393, t394);
    return ____25list(t1509, t1512);
   };
   return ___call_2dwith_2dvalues(t1503, t1505, t1508);
  };
  var t1515 = SPOCK.intern("selected-square");
  return ___assoc_2dval(t1502, t1515, t382);
 };
 var t1517 = function (k718, t383) {
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1518 = function (t726) {
   var t386 = t726;
   var t725 = t386;
   var t1519 = function (t719) {
    var t1520 = function (t721) {
     var t1521 = function (t720) {
      var t387 = t720;
      return k718(t387);
     };
     return ____25list(t1521, t721);
    };
    var t1524 = SPOCK.intern("selected-square");
    return ___assoc(t1520, t1524, ____2ainits_2a);
   };
   var t1526 = function (k722, t384) {
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t1527 = SPOCK.intern("continuations");
    var t1528 = function (k723, t385) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1529 = function (t724) {
      return t383(k723, t724);
     };
     return ___append(t1529, t385, t382);
    };
    return ___put_2dcons_21(k722, t384, t1527, t1528);
   };
   return ___map(t1519, t1526, t725);
  };
  var t1534 = SPOCK.intern("selected-square");
  return ____25list(t1518, t1534);
 };
 return ___call_2fcc(t1501, t1517);
};
SPOCK.run(t1500);
var t1537 = function (k727) {
 var t395 = undefined;
 var t1538 = function (t739) {
  t395 = t739;	// set! t395
  var t728 = undefined;
  var t1539 = function (t730) {
   var t401 = t730;
   var t1540 = function (t729) {
    return ___yield(k727);
   };
   var t1542 = function (k731, t402) {
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t1543 = function(k1544, x) { return k1544(x.currentTarget); }
    var t1545 = function (t738) {
     var t1546 = function(k1547, x) { return k1547(x.responseXML); }
     var t1548 = function (t737) {
      var t1549 = function (t732) {
       var t1550 = function (k733) {
        loop: while(true) {
         var t403 = t401;
         var t404 = 2;
         var t1551 = (t403)  +  (t404);
         return k733(t1551);
        }
       };
       var t1553 = function (k734, t405) {
        var r = SPOCK.count(arguments);
        if(r) return r;
        var t1554 = function (t736) {
         var t406 = t736;
         var t735 = t406;
         return ___send_2dvars(k734, t735);
        };
        var t1556 = SPOCK.intern("selected");
        var t407 = t1556;
        var t408 = t405;
        var t1557 = new SPOCK.Pair(t407, t408);
        return ____25list(t1554, t1557);
       };
       return ___call_2dwith_2dvalues(k731, t1550, t1553);
      };
      return ___log(t1549, t737);
     };
     return t1546(t1548, t738);
    };
    return t1543(t1545, t402);
   };
   return ___ajax(t1540, "GET", "http://lookup.dbpedia.org/api/search.asmx/PrefixSearch?QueryClass=&MaxHits=5&QueryString=Brussels", t1542);
  };
  var t1564 = SPOCK.intern("selected-square");
  return ___assoc_2dval(t1539, t1564, t395);
 };
 var t1566 = function (k740, t396) {
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1567 = function (t748) {
   var t399 = t748;
   var t747 = t399;
   var t1568 = function (t741) {
    var t1569 = function (t743) {
     var t1570 = function (t742) {
      var t400 = t742;
      return k740(t400);
     };
     return ____25list(t1570, t743);
    };
    var t1573 = SPOCK.intern("selected-square");
    return ___assoc(t1569, t1573, ____2ainits_2a);
   };
   var t1575 = function (k744, t397) {
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t1576 = SPOCK.intern("continuations");
    var t1577 = function (k745, t398) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1578 = function (t746) {
      return t396(k745, t746);
     };
     return ___append(t1578, t398, t395);
    };
    return ___put_2dcons_21(k744, t397, t1576, t1577);
   };
   return ___map(t1568, t1575, t747);
  };
  var t1583 = SPOCK.intern("selected-square");
  return ____25list(t1567, t1583);
 };
 return ___call_2fcc(t1538, t1566);
};
SPOCK.run(t1537);
var t1586 = function (k749) {
 var t1587 = function (k750, t409) {
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   ___waiting = t409;	// set! waiting
   return k750(undefined);
  }
 };
 return ___call_2fcc(k749, t1587);
};
SPOCK.run(t1586);
var t1590 = function (k751) {
 return ___print(k751, "waiting...");
};
SPOCK.run(t1590);
SPOCK.flush();
/* END OF GENERATED CODE */
