/* CODE GENERATED BY SPOCK 0 */
var t607 = function (k323) {
 var t608 = function (k324, t1, t2) {	// qsa
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t609 = t1.querySelectorAll(t2);
   return k324(t609);
  }
 };
 ___qsa = t608;	// set! qsa
 var t611 = function (k325, t3, t4) {	// qs
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t612 = t3.querySelector(t4);
   return k325(t612);
  }
 };
 ___qs = t611;	// set! qs
 var t614 = function (k326, t5, t6) {	// dqsa
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t615 = document.body.querySelectorAll(t6);
   return k326(t615);
  }
 };
 ___dqsa = t614;	// set! dqsa
 var t617 = function (k327, t7, t8) {	// dqs
  var r = SPOCK.count(arguments);
  if(r) return r;
  return ___qs(k327, document.body, t8);
 };
 ___dqs = t617;	// set! dqs
 var t619 = function (k328, t9) {	// log
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t620 = console.log(t9);
   return k328(t620);
  }
 };
 ___log = t619;	// set! log
 var t622 = function (k329, t10) {	// alert
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t623 = window.alert(t10);
   return k329(t623);
  }
 };
 ___alert = t622;	// set! alert
 var t625 = function (k330, t11) {	// get-id
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t626 = document.getElementById(t11);
   return k330(t626);
  }
 };
 ___get_2did = t625;	// set! get-id
 var t628 = function (k331, t12, t13, t14) {	// new-element
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t629 = document.createElement(t12);
  var t15 = t629;
  var t630;
  if(t14 !== false) {
   var t631 = t15.classList.add(t14);
   t630 = t631;
  }
  else {
  }
  var t632 = function (t332) {
   return k331(t15);
  };
  var t634 = function (k333, t16) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   loop: while(true) {
    var t635 = t15.appendChild(t16);
    return k333(t635);
   }
  };
  return ___for_2deach(t632, t634, t13);
 };
 ___new_2delement = t628;	// set! new-element
 var t638 = function (k334, t17) {	// <text>
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t639 = document.createTextNode(t17);
   return k334(t639);
  }
 };
 ____3ctext_3e = t638;	// set! <text>
 var t641 = function (k335, t18) {	// remove-node
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t642 = function(k643, x) { return k643(x.parentNode); }
  var t644 = function (t336) {
   var t645 = t336.removeChild(t18);
   return k335(t645);
  };
  return t642(t644, t18);
 };
 ___remove_2dnode = t641;	// set! remove-node
 var t648 = function (k337, t19, t20) {	// insert-node-before
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t649 = function(k650, x) { return k650(x.parentNode); }
  var t651 = function (t338) {
   var t652 = t338.insertBefore(t19, t20);
   return k337(t652);
  };
  return t649(t651, t20);
 };
 ___insert_2dnode_2dbefore = t648;	// set! insert-node-before
 var t655 = function (k339, t21, t22) {	// replace-node
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t656 = function(k657, x) { return k657(x.parentNode); }
  var t658 = function (t340) {
   var t659 = t340.replaceChild(t21, t22);
   return k339(t659);
  };
  return t656(t658, t22);
 };
 ___replace_2dnode = t655;	// set! replace-node
 var t662 = function (k341, t23, t24) {	// node-append-child
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t663 = t23.appendChild(t24);
   return k341(t663);
  }
 };
 ___node_2dappend_2dchild = t662;	// set! node-append-child
 var t665 = function (k342, t25, t26) {	// set-html
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t25.innerHTML = t26;
   return k342(t26);
  }
 };
 ___set_2dhtml = t665;	// set! set-html
 var t667 = new diffDOM();
 ___dd = t667;	// set! dd
 var t668 = function (k343, t27, t28) {	// patch
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t670 = ___dd.diff(t27, t28);
   var t669 = ___dd.apply(t27, t670);
   return k343(t669);
  }
 };
 ___patch = t668;	// set! patch
 var t672 = function (k344) {	// spock-elements
  loop: while(true) {
   var t674 = document.body.querySelectorAll("*[spock]");
   var t673 = Array.prototype.slice.call(t674);
   return k344(t673);
  }
 };
 ___spock_2delements = t672;	// set! spock-elements
 var t676 = function (k345, t29, t30, t31) {	// add-event-listener
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t677 = t30.addEventListener(t29, t31);
   return k345(t677);
  }
 };
 ___add_2devent_2dlistener = t676;	// set! add-event-listener
 var t679 = function (k346, t32, t33) {	// set-click
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t32.onclick = t33;
   return k346(t32);
  }
 };
 ___set_2dclick = t679;	// set! set-click
 var t681 = function (k347, t34, t35) {	// set-click2
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t34.onclick = t35;
   return k347(t34);
  }
 };
 ___set_2dclick2 = t681;	// set! set-click2
 var t683 = function (k348, t36, t37) {	// ajax
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t684 = new XMLHttpRequest();
  var t38 = t684;
  var t685 = function (t349) {
   var t686 = t38.open(t36, t37, true);
   var t687 = function (k350) {	// t39
    var t688 = alert(5);
    var t689 = function(k690, x) { return k690(x.responseText); }
    var t691 = function (t351) {
     return ___log(k350, t351);
    };
    return t689(t691, t38);
   };
   var t39 = t687;
   var t694 = SPOCK.callback(t39);
   t38.onreadystatechange = t694;
   var t695 = t38.send();
   return k348(t695);
  };
  return ___log(t685, t38);
 };
 ___ajax = t683;	// set! ajax
 var t698 = function (k352, t40, t41) {	// register-callback
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t699 = function (t353) {	// t354
   var t42 = t353;
   var t700 = SPOCK.intern("callback");
   return ___put_21(k352, t42, t700, t41);
  };
  var t354 = t699;
  var t43 = t40;
  var t703 = typeof(t43);
  var t45 = t703;
  var t46 = "string";
  var t704 = (t45) === (t46);
  var t44 = t704;
  var t705;
  if(t44 !== false) {
   t705 = t44;
  }
  else {
   var t706 = (t43) instanceof SPOCK.String ;
   t705 = t706;
  }
  var t702;
  if(t705 !== false) {
   return ___string_2d_3esymbol(t354, t40);
  }
  else {
   return t354(t40);
  }
 };
 ___register_2dcallback = t698;	// set! register-callback
 var t709 = function (k355, t47) {	// get-callback
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t710 = function (t356) {	// t357
   var t48 = t356;
   var t711 = SPOCK.intern("callback");
   return ___get(k355, t48, t711);
  };
  var t357 = t710;
  var t49 = t47;
  var t714 = typeof(t49);
  var t51 = t714;
  var t52 = "string";
  var t715 = (t51) === (t52);
  var t50 = t715;
  var t716;
  if(t50 !== false) {
   t716 = t50;
  }
  else {
   var t717 = (t49) instanceof SPOCK.String ;
   t716 = t717;
  }
  var t713;
  if(t716 !== false) {
   return ___string_2d_3esymbol(t357, t47);
  }
  else {
   return t357(t47);
  }
 };
 ___get_2dcallback = t709;	// set! get-callback
 var t720 = function (k358) {	// waiting
  loop: while(true) {
   return k358(false);
  }
 };
 ___waiting = t720;	// set! waiting
 ___call_2fcc = ___call_2dwith_2dcurrent_2dcontinuation;	// set! call/cc
 var t722 = null;
 ____2aqueue_2a = t722;	// set! *queue*
 var t723 = function (k359, t53) {	// *enqueue*
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t724 = function (t362) {
   var t54 = t362;
   var t361 = t54;
   var t725 = function (t360) {
    ____2aqueue_2a = t360;	// set! *queue*
    return k359(undefined);
   };
   return ___append(t725, ____2aqueue_2a, t361);
  };
  return ____25list(t724, t53);
 };
 ____2aenqueue_2a = t723;	// set! *enqueue*
 var t729 = function (k363) {	// *dequeue*
  loop: while(true) {
   var t56 = ____2aqueue_2a;
   var t57 = t56;
   var t730 = t57.car;
   var t55 = t730;
   var t58 = ____2aqueue_2a;
   var t59 = t58;
   var t731 = t59.cdr;
   ____2aqueue_2a = t731;	// set! *queue*
   return k363(t55);
  }
 };
 ____2adequeue_2a = t729;	// set! *dequeue*
 var t733 = function (k364) {	// yield
  var t60 = ____2aqueue_2a;
  var t61 = t60;
  var t735 = null;
  var t62 = t735;
  var t736 = (t61) === (t62);
  var t734;
  if(t736 !== false) {
   return ___waiting(k364);
  }
  else {
   var t738 = function (t365) {
    var t63 = t365;
    var t739 = function (t366) {
     var t740 = function (t367) {
      return t367(k364);
     };
     return t63(t740);
    };
    return ___print(t739, "YIELDING");
   };
   return ____2adequeue_2a(t738);
  }
 };
 ___yield = t733;	// set! yield
 var t745 = function (k368, t64, t65) {	// assoc-val
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t746 = function (t369) {
   var t66 = t369;
   var t67 = t66;
   var t747 = t67.cdr;
   return k368(t747);
  };
  return ___assoc(t746, t64, t65);
 };
 ___assoc_2dval = t745;	// set! assoc-val
 ___merge_2dbindings = ___append;	// set! merge-bindings
 var t750 = function (k370, t68, t69) {	// get-binding
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t751 = function (t371) {
   var t70 = t371;
   var t752;
   if(t70 !== false) {
    var t71 = t70;
    var t72 = t71;
    var t753 = t72.cdr;
    t752 = t753;
   }
   else {
    t752 = false;
   }
   return k370(t752);
  };
  return ___assoc(t751, t68, t69);
 };
 ___get_2dbinding = t750;	// set! get-binding
 var t756 = function (k372, t73, t74) {	// send-bindings
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t757 = function (t373) {
   return t373(k372, t74);
  };
  var t759 = SPOCK.intern("continuations");
  return ___get(t757, t73, t759);
 };
 ___send_2dbindings = t756;	// set! send-bindings
 var t761 = function (k374, t75, t76) {	// three-way-split
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t77 = undefined;
  var t762 = function (k375, t78, t79, t80, t81, t82) {	// t77
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t83 = t79;
   var t84 = t83;
   var t764 = null;
   var t85 = t764;
   var t765 = (t84) === (t85);
   var t763;
   if(t765 !== false) {
    var t766 = function (t377) {
     var t767 = function (t376) {
      var t86 = t376;
      return k375(t86);
     };
     return ____25list(t767, t377, t81, t82);
    };
    return ___append(t766, t78, t80);
   }
   else {
    var t88 = t79;
    var t89 = t88;
    var t771 = t89.car;
    var t87 = t771;
    var t90 = undefined;
    var t772 = function (k378, t91, t92) {	// t90
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t93 = t91;
     var t94 = t93;
     var t774 = null;
     var t95 = t774;
     var t775 = (t94) === (t95);
     var t773;
     if(t775 !== false) {
      var t96 = t79;
      var t97 = t96;
      var t776 = t97.cdr;
      var t98 = t87;
      var t99 = t82;
      var t777 = new SPOCK.Pair(t98, t99);
      return t77(k378, t92, t776, t80, t81, t777);
     }
     else {
      var t101 = t91;
      var t102 = t101;
      var t779 = t102.car;
      var t100 = t779;
      var t103 = t87;
      var t104 = t100;
      var t781 = SPOCK.equalp(t103, t104);
      var t780;
      if(t781 !== false) {
       var t782 = function (t379) {
        var t107 = t79;
        var t108 = t107;
        var t783 = t108.cdr;
        var t109 = t87;
        var t110 = t81;
        var t784 = new SPOCK.Pair(t109, t110);
        return t77(k378, t379, t783, t80, t784, t82);
       };
       var t105 = t91;
       var t106 = t105;
       var t786 = t106.cdr;
       return ___append(t782, t92, t786);
      }
      else {
       var t111 = t91;
       var t112 = t111;
       var t788 = t112.cdr;
       var t113 = t100;
       var t114 = t92;
       var t789 = new SPOCK.Pair(t113, t114);
       return t90(k378, t788, t789);
      }
      t773 = t780;
     }
    };
    t90 = t772;	// set! t90
    var t791 = null;
    return t90(k375, t78, t791);
   }
  };
  t77 = t762;	// set! t77
  var t793 = null;
  var t794 = null;
  var t795 = null;
  return t77(k374, t75, t76, t793, t794, t795);
 };
 ___three_2dway_2dsplit = t761;	// set! three-way-split
 var t797 = function (k380, t115, t116) {	// merge-alist-sets
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t118 = t116;
  var t119 = t118;
  var t798 = t119.car;
  var t117 = t798;
  var t120 = undefined;
  var t799 = function (k381, t121, t122, t123) {	// t120
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t125 = t122;
   var t126 = t125;
   var t801 = null;
   var t127 = t801;
   var t802 = (t126) === (t127);
   var t124 = t802;
   var t803;
   if(t124 !== false) {
    t803 = t124;
   }
   else {
    var t128 = t121;
    var t129 = t128;
    var t804 = null;
    var t130 = t804;
    var t805 = (t129) === (t130);
    t803 = t805;
   }
   var t800;
   if(t803 !== false) {
    var t806 = function (t384) {
     var t135 = t384;
     var t383 = t135;
     var t133 = t383;
     var t134 = t122;
     var t807 = new SPOCK.Pair(t133, t134);
     var t382 = t807;
     var t131 = t382;
     var t132 = t123;
     var t808 = new SPOCK.Pair(t131, t132);
     return k381(t808);
    };
    return ____25list(t806, t117);
   }
   else {
    var t137 = t121;
    var t139 = t137;
    var t140 = t139;
    var t811 = t140.car;
    var t138 = t811;
    var t141 = t138;
    var t812 = t141.car;
    var t136 = t812;
    var t143 = t121;
    var t145 = t143;
    var t146 = t145;
    var t813 = t146.car;
    var t144 = t813;
    var t147 = t144;
    var t814 = t147.cdr;
    var t142 = t814;
    var t815 = function (t385) {
     var t148 = t385;
     var t150 = t148;
     var t151 = t150;
     var t816 = t151.car;
     var t149 = t816;
     var t153 = t148;
     var t155 = t153;
     var t156 = t155;
     var t817 = t156.cdr;
     var t154 = t817;
     var t157 = t154;
     var t818 = t157.car;
     var t152 = t818;
     var t819 = function (t386) {
      var t158 = t386;
      var t820 = function (t389) {
       var t161 = t389;
       var t388 = t161;
       var t821 = function (t387) {
        var t159 = t121;
        var t160 = t159;
        var t822 = t160.cdr;
        return t120(k381, t822, t158, t387);
       };
       return ___append(t821, t388, t123);
      };
      var t162 = t136;
      var t163 = t149;
      var t825 = new SPOCK.Pair(t162, t163);
      var t166 = t117;
      var t167 = t136;
      var t826 = new SPOCK.Pair(t166, t167);
      var t164 = t826;
      var t165 = t152;
      var t827 = new SPOCK.Pair(t164, t165);
      return ____25list(t820, t825, t827);
     };
     return ___caddr(t819, t148);
    };
    return ___three_2dway_2dsplit(t815, t142, t122);
   }
  };
  t120 = t799;	// set! t120
  var t168 = t116;
  var t169 = t168;
  var t831 = t169.cdr;
  var t832 = null;
  return t120(k380, t115, t831, t832);
 };
 ___merge_2dalist_2dsets = t797;	// set! merge-alist-sets
 var t834 = function (k390, t170) {	// merge-continuation-lists
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t171 = undefined;
  var t835 = function (k391, t172, t173) {	// t171
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t174 = t173;
   var t175 = t174;
   var t837 = null;
   var t176 = t837;
   var t838 = (t175) === (t176);
   var t836;
   if(t838 !== false) {
    return k391(t172);
   }
   else {
    var t840 = function (t392) {
     var t179 = t173;
     var t180 = t179;
     var t841 = t180.cdr;
     return t171(k391, t392, t841);
    };
    var t177 = t173;
    var t178 = t177;
    var t843 = t178.car;
    return ___merge_2dalist_2dsets(t840, t172, t843);
   }
  };
  t171 = t835;	// set! t171
  var t845 = null;
  return t171(k390, t845, t170);
 };
 ___merge_2dcontinuation_2dlists = t834;	// set! merge-continuation-lists
 var t847 = function (k393, t181) {	// merge-continuation-lists2
  var r = SPOCK.count(arguments);
  if(r) return r;
  return ___append(k393, t181);
 };
 ___merge_2dcontinuation_2dlists2 = t847;	// set! merge-continuation-lists2
 var t849 = function (k394, t182) {	// send-vars
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t850 = function (t402) {
   var t851 = function (t401) {
    var t852 = function (t395) {
     var t853 = function (t396) {
      return ___yield(k394);
     };
     return ___print(t853, "QUEUE: ", ____2aqueue_2a);
    };
    var t856 = function (k397, t183) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t857 = function (t398) {
      var t186 = t183;
      var t187 = t186;
      var t858 = t187.car;
      var t184 = t858;
      var t188 = t183;
      var t189 = t188;
      var t859 = t189.cdr;
      var t185 = t859;
      var t191 = t185;
      var t192 = t191;
      var t861 = null;
      var t193 = t861;
      var t862 = (t192) === (t193);
      var t190 = t862;
      var t863;
      if(t190 !== false) {
       t863 = false;
      }
      else {
       t863 = true;
      }
      var t860;
      if(t863 !== false) {
       var t864 = function (k399, t194) {
        var r = SPOCK.count(arguments);
        if(r) return r;
        var t865 = function (k400) {
         return t194(k400, t182);
        };
        return ____2aenqueue_2a(k399, t865);
       };
       return ___map(k397, t864, t185);
      }
      else {
       return k397(undefined);
      }
     };
     return ___print(t857, "CONTINUATIONS: ", t183);
    };
    return ___map(t852, t856, t401);
   };
   return ___merge_2dcontinuation_2dlists(t851, t402);
  };
  var t873 = function (k403, t195) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t197 = t195;
   var t198 = t197;
   var t874 = t198.car;
   var t196 = t874;
   var t199 = t196;
   var t875 = function (t404) {
    var t200 = t404;
    var t876 = new SPOCK.Pair(t199, t200);
    return k403(t876);
   };
   var t878 = SPOCK.intern("continuations");
   return ___get(t875, t196, t878);
  };
  return ___map(t850, t873, t182);
 };
 ___send_2dvars = t849;	// set! send-vars
 var t881 = function (k405, t201) {	// remove-all-children
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t882 = function (k406, t202) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   loop: while(true) {
    var t883 = t201.removeChild(t202);
    return k406(t883);
   }
  };
  var t886 = t201.childNodes;
  var t885 = Array.prototype.slice.call(t886);
  return ___for_2deach(k405, t882, t885);
 };
 ___remove_2dall_2dchildren = t881;	// set! remove-all-children
 var t888 = function (k407, t203) {	// init
  var r = SPOCK.count(arguments);
  if(r) return r;
  ____2ainits_2a = t203;	// set! *inits*
  var t889 = function (t413) {
   var t890 = function (t408) {
    var t891 = function (t409) {
     return ___print(k407, "waiting...");
    };
    var t893 = function (k410, t206) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     loop: while(true) {
      ___waiting = t206;	// set! waiting
      return k410(undefined);
     }
    };
    return ___call_2fcc(t891, t893);
   };
   var t896 = function (k411, t204) {
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t897 = t204.getAttribute("spock");
    var t205 = t897;
    var t898 = function (t412) {
     return t412(k411, t204);
    };
    return ___get_2dcallback(t898, t205);
   };
   return ___map(t890, t896, t413);
  };
  return ___spock_2delements(t889);
 };
 ___init = t888;	// set! init
 var t903 = function (k414, t207) {	// click1
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t904 = null;
  var t208 = t904;
  var t905 = function (t415) {
   var t209 = t415;
   var t906 = function (t419) {
    t208 = t419;	// set! t208
    var t416 = undefined;
    var t907 = function (t417) {
     return ___yield(k414);
    };
    var t909 = function (k418, t218) {	// t217
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t910 = new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("status"), "Loading..."), null);
     var t219 = t910;
     return ___send_2dvars(k418, t219);
    };
    var t217 = t909;
    var t912 = SPOCK.callback(t217);
    return ___set_2dclick(t907, t207, t912);
   };
   return ___merge_2dbindings(t906, t209, t208);
  };
  var t915 = function (k420, t210) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t916 = function (t430) {
    var t215 = t430;
    var t429 = t215;
    var t917 = function (t421) {
     var t918 = function (t422) {
      var t216 = t422;
      return k420(t216);
     };
     return ____25list(t918);
    };
    var t921 = function (k423, t211) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t922 = function (t428) {
      var t923 = function (t424) {
       var t212 = t210;
       var t924 = function (t427) {
        var t214 = t427;
        var t925;
        if(t214 !== false) {
         t925 = t214;
        }
        else {
         var t926 = null;
         t925 = t926;
        }
        var t426 = t925;
        var t213 = t426;
        var t927 = new SPOCK.Pair(t212, t213);
        var t425 = t927;
        var t928 = SPOCK.intern("continuations");
        return ___put_21(k423, t211, t928, t425);
       };
       var t930 = SPOCK.intern("continuations");
       return ___get(t924, t211, t930);
      };
      return ___print(t923, "putting ", t211, ": ", t210, " into ", t428);
     };
     var t933 = SPOCK.intern("continuations");
     return ___get(t922, t211, t933);
    };
    return ___map(t917, t921, t429);
   };
   return ____25list(t916);
  };
  return ___call_2fcc(t905, t915);
 };
 ___click1 = t903;	// set! click1
 return ___register_2dcallback(k323, "click1", ___click1);
};
SPOCK.run(t607);
var t939 = function (k431) {
 var t940 = function (k432, t220) {	// click2
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t941 = null;
  var t221 = t941;
  var t942 = function (t433) {
   var t222 = t433;
   var t943 = function (t440) {
    t221 = t440;	// set! t221
    var t434 = undefined;
    var t944 = function (t436) {
     var t230 = t436;
     var t945 = function (t435) {
      return ___yield(k432);
     };
     var t947 = function (k437, t232) {	// t231
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t948 = function (t439) {
       var t234 = t439;
       var t438 = t234;
       var t233 = t438;
       return ___send_2dvars(k437, t233);
      };
      var t950 = SPOCK.intern("count");
      var t235 = t950;
      var t237 = t230;
      var t238 = 1;
      var t951 = (t237)  +  (t238);
      var t236 = t951;
      var t952 = new SPOCK.Pair(t235, t236);
      return ____25list(t948, t952);
     };
     var t231 = t947;
     var t954 = SPOCK.callback(t231);
     return ___set_2dclick(t945, t220, t954);
    };
    var t956 = SPOCK.intern("count");
    return ___assoc_2dval(t944, t956, t221);
   };
   return ___merge_2dbindings(t943, t222, t221);
  };
  var t959 = function (k441, t223) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t960 = function (t452) {
    var t228 = t452;
    var t451 = t228;
    var t961 = function (t442) {
     var t962 = function (t444) {
      var t963 = function (t443) {
       var t229 = t443;
       return k441(t229);
      };
      return ____25list(t963, t444);
     };
     var t966 = SPOCK.intern("count");
     return ___assoc(t962, t966, ____2ainits_2a);
    };
    var t968 = function (k445, t224) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t969 = function (t450) {
      var t970 = function (t446) {
       var t225 = t223;
       var t971 = function (t449) {
        var t227 = t449;
        var t972;
        if(t227 !== false) {
         t972 = t227;
        }
        else {
         var t973 = null;
         t972 = t973;
        }
        var t448 = t972;
        var t226 = t448;
        var t974 = new SPOCK.Pair(t225, t226);
        var t447 = t974;
        var t975 = SPOCK.intern("continuations");
        return ___put_21(k445, t224, t975, t447);
       };
       var t977 = SPOCK.intern("continuations");
       return ___get(t971, t224, t977);
      };
      return ___print(t970, "putting ", t224, ": ", t223, " into ", t450);
     };
     var t980 = SPOCK.intern("continuations");
     return ___get(t969, t224, t980);
    };
    return ___map(t961, t968, t451);
   };
   var t983 = SPOCK.intern("count");
   return ____25list(t960, t983);
  };
  return ___call_2fcc(t942, t959);
 };
 ___click2 = t940;	// set! click2
 return ___register_2dcallback(k431, "click2", ___click2);
};
SPOCK.run(t939);
var t987 = function (k453) {
 var t988 = function (k454, t239, t240) {	// range
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t241 = t239;
  var t242 = t240;
  var t990 = SPOCK.equalp(t241, t242);
  var t989;
  if(t990 !== false) {
   var t991 = null;
   return k454(t991);
  }
  else {
   var t243 = t239;
   var t993 = function (t455) {
    var t244 = t455;
    var t994 = new SPOCK.Pair(t243, t244);
    return k454(t994);
   };
   var t245 = 1;
   var t246 = t239;
   var t996 = (t245)  +  (t246);
   return ___range(t993, t996, t240);
  }
 };
 ___range = t988;	// set! range
 var t998 = function (k456, t247) {	// click0
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t999 = null;
  var t248 = t999;
  var t1000 = function (t457) {
   var t249 = t457;
   var t1001 = function (t466) {
    t248 = t466;	// set! t248
    var t458 = undefined;
    var t1002 = function (t460) {
     var t257 = t460;
     var t1003 = function (t459) {
      return ___yield(k456);
     };
     var t1005 = function (k461, t259) {	// t258
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t1006 = SPOCK.intern("messages");
      var t262 = t1006;
      var t1007 = function (t465) {
       var t263 = t465;
       var t1008 = new SPOCK.Pair(t262, t263);
       var t464 = t1008;
       var t1009 = function (t463) {
        var t261 = t463;
        var t462 = t261;
        var t260 = t462;
        return ___send_2dvars(k461, t260);
       };
       return ____25list(t1009, t464);
      };
      return ___range(t1007, 0, t257);
     };
     var t258 = t1005;
     var t1013 = SPOCK.callback(t258);
     return ___set_2dclick(t1003, t247, t1013);
    };
    var t1015 = SPOCK.intern("count");
    return ___assoc_2dval(t1002, t1015, t248);
   };
   return ___merge_2dbindings(t1001, t249, t248);
  };
  var t1018 = function (k467, t250) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1019 = function (t478) {
    var t255 = t478;
    var t477 = t255;
    var t1020 = function (t468) {
     var t1021 = function (t470) {
      var t1022 = function (t469) {
       var t256 = t469;
       return k467(t256);
      };
      return ____25list(t1022, t470);
     };
     var t1025 = SPOCK.intern("count");
     return ___assoc(t1021, t1025, ____2ainits_2a);
    };
    var t1027 = function (k471, t251) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1028 = function (t476) {
      var t1029 = function (t472) {
       var t252 = t250;
       var t1030 = function (t475) {
        var t254 = t475;
        var t1031;
        if(t254 !== false) {
         t1031 = t254;
        }
        else {
         var t1032 = null;
         t1031 = t1032;
        }
        var t474 = t1031;
        var t253 = t474;
        var t1033 = new SPOCK.Pair(t252, t253);
        var t473 = t1033;
        var t1034 = SPOCK.intern("continuations");
        return ___put_21(k471, t251, t1034, t473);
       };
       var t1036 = SPOCK.intern("continuations");
       return ___get(t1030, t251, t1036);
      };
      return ___print(t1029, "putting ", t251, ": ", t250, " into ", t476);
     };
     var t1039 = SPOCK.intern("continuations");
     return ___get(t1028, t251, t1039);
    };
    return ___map(t1020, t1027, t477);
   };
   var t1042 = SPOCK.intern("count");
   return ____25list(t1019, t1042);
  };
  return ___call_2fcc(t1000, t1018);
 };
 ___click0 = t998;	// set! click0
 return ___register_2dcallback(k453, "click0", ___click0);
};
SPOCK.run(t987);
var t1046 = function (k479) {
 var t1047 = function (k480, t264) {	// single-render
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1048 = null;
  var t265 = t1048;
  var t1049 = function (t481) {
   var t266 = t481;
   var t1050 = function (t495) {
    t265 = t495;	// set! t265
    var t482 = undefined;
    var t1051 = function (t484) {
     var t274 = t484;
     var t1052 = function (t494) {
      var t1053 = function (t493) {
       var t277 = t493;
       var t492 = t277;
       var t1054 = function (t485) {
        var t275 = t485;
        var t1055 = t264.cloneNode(false);
        var t276 = t1055;
        var t1056 = function (t486) {
         var t1057 = function (t487) {	// t489
          var t1058 = function (t488) {
           t264 = t276;	// set! t264
           var t483 = undefined;
           return ___yield(k480);
          };
          return ___replace_2dnode(t1058, t276, t264);
         };
         var t489 = t1057;
         var t1061 = function (t490) {
          var t1062;
          if(t490 !== false) {
           var t1063 = function (k491, t278) {
            var r = SPOCK.count(arguments);
            if(r) return r;
            return ___node_2dappend_2dchild(k491, t276, t278);
           };
           return ___for_2deach(t489, t1063, t275);
          }
          else {
           return ___node_2dappend_2dchild(t489, t276, t275);
          }
         };
         return ___list_3f(t1061, t275);
        };
        return ___log(t1056, t275);
       };
       return ___new_2delement(t1054, "div", t492, "class");
      };
      return ____25list(t1053, t494);
     };
     return ____3ctext_3e(t1052, t274);
    };
    var t1072 = SPOCK.intern("status");
    return ___assoc_2dval(t1051, t1072, t265);
   };
   return ___merge_2dbindings(t1050, t266, t265);
  };
  var t1075 = function (k496, t267) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1076 = function (t507) {
    var t272 = t507;
    var t506 = t272;
    var t1077 = function (t497) {
     var t1078 = function (t499) {
      var t1079 = function (t498) {
       var t273 = t498;
       return k496(t273);
      };
      return ____25list(t1079, t499);
     };
     var t1082 = SPOCK.intern("status");
     return ___assoc(t1078, t1082, ____2ainits_2a);
    };
    var t1084 = function (k500, t268) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1085 = function (t505) {
      var t1086 = function (t501) {
       var t269 = t267;
       var t1087 = function (t504) {
        var t271 = t504;
        var t1088;
        if(t271 !== false) {
         t1088 = t271;
        }
        else {
         var t1089 = null;
         t1088 = t1089;
        }
        var t503 = t1088;
        var t270 = t503;
        var t1090 = new SPOCK.Pair(t269, t270);
        var t502 = t1090;
        var t1091 = SPOCK.intern("continuations");
        return ___put_21(k500, t268, t1091, t502);
       };
       var t1093 = SPOCK.intern("continuations");
       return ___get(t1087, t268, t1093);
      };
      return ___print(t1086, "putting ", t268, ": ", t267, " into ", t505);
     };
     var t1096 = SPOCK.intern("continuations");
     return ___get(t1085, t268, t1096);
    };
    return ___map(t1077, t1084, t506);
   };
   var t1099 = SPOCK.intern("status");
   return ____25list(t1076, t1099);
  };
  return ___call_2fcc(t1049, t1075);
 };
 ___single_2drender = t1047;	// set! single-render
 return ___register_2dcallback(k479, "single-render", ___single_2drender);
};
SPOCK.run(t1046);
var t1103 = function (k508) {
 var t1104 = function (k509, t279) {	// map-render3
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1105 = null;
  var t280 = t1105;
  var t1106 = function (t510) {
   var t281 = t510;
   var t1107 = function (t542) {
    t280 = t542;	// set! t280
    var t511 = undefined;
    var t1108 = function (t513) {
     var t289 = t513;
     var t1109 = function (t514) {
      var t290 = t514;
      var t1110 = t279.cloneNode(false);
      var t291 = t1110;
      var t1111 = function (t515) {
       var t1112 = function (t516) {
        t279 = t291;	// set! t279
        var t512 = undefined;
        return ___yield(k509);
       };
       return ___replace_2dnode(t1112, t291, t279);
      };
      var t1115 = function (k517, t292) {
       var r = SPOCK.count(arguments);
       if(r) return r;
       var t1116 = function (t541) {
        var t1117 = function (t540) {
         var t295 = t540;
         var t539 = t295;
         var t1118 = function (t538) {
          var t1119 = function (t537) {
           var t294 = t537;
           var t536 = t294;
           var t1120 = function (t521) {
            var t1121 = function (t535) {
             var t1122 = function (t534) {
              var t296 = t534;
              var t533 = t296;
              var t1123 = function (t522) {
               var t1124 = function (t532) {
                var t1125 = function (t531) {
                 var t298 = t531;
                 var t530 = t298;
                 var t1126 = function (t527) {
                  var t1127 = function (t526) {
                   var t1128 = function (t525) {
                    var t297 = t525;
                    var t524 = t297;
                    var t1129 = function (t523) {
                     var t1130 = function (t520) {
                      var t293 = t520;
                      var t519 = t293;
                      var t1131 = function (t518) {
                       return ___node_2dappend_2dchild(k517, t291, t518);
                      };
                      return ___new_2delement(t1131, "div", t519, "class");
                     };
                     return ____25list(t1130, t521, t522, t523);
                    };
                    return ___new_2delement(t1129, "div", t524, "class");
                   };
                   return ____25list(t1128, t526);
                  };
                  var t1137 = function (k528) {	// t299
                   var t1138 = function (t529) {
                    var t1139 = new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("status"), "reloading"), null);
                    return k528(t1139);
                   };
                   return ___print(t1138, "yay ", t292);
                  };
                  var t299 = t1137;
                  var t1142 = SPOCK.callback(t299);
                  return ___set_2dclick(t1127, t527, t1142);
                 };
                 return ___new_2delement(t1126, "button", t530, "class");
                };
                return ____25list(t1125, t532);
               };
               return ____3ctext_3e(t1124, "click me");
              };
              return ___new_2delement(t1123, "div", t533, "class");
             };
             return ____25list(t1122, t535);
            };
            return ____3ctext_3e(t1121, t290);
           };
           return ___new_2delement(t1120, "div", t536, "class");
          };
          return ____25list(t1119, t538);
         };
         return ___new_2delement(t1118, "b", t539, "class");
        };
        return ____25list(t1117, t541);
       };
       return ____3ctext_3e(t1116, t292);
      };
      return ___for_2deach(t1111, t1115, t289);
     };
     var t1156 = SPOCK.intern("count");
     return ___assoc_2dval(t1109, t1156, t280);
    };
    var t1158 = SPOCK.intern("messages");
    return ___assoc_2dval(t1108, t1158, t280);
   };
   return ___merge_2dbindings(t1107, t281, t280);
  };
  var t1161 = function (k543, t282) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1162 = function (t555) {
    var t287 = t555;
    var t554 = t287;
    var t1163 = function (t544) {
     var t1164 = function (t546) {
      var t1165 = function (t547) {
       var t1166 = function (t545) {
        var t288 = t545;
        return k543(t288);
       };
       return ____25list(t1166, t546, t547);
      };
      var t1169 = SPOCK.intern("count");
      return ___assoc(t1165, t1169, ____2ainits_2a);
     };
     var t1171 = SPOCK.intern("messages");
     return ___assoc(t1164, t1171, ____2ainits_2a);
    };
    var t1173 = function (k548, t283) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1174 = function (t553) {
      var t1175 = function (t549) {
       var t284 = t282;
       var t1176 = function (t552) {
        var t286 = t552;
        var t1177;
        if(t286 !== false) {
         t1177 = t286;
        }
        else {
         var t1178 = null;
         t1177 = t1178;
        }
        var t551 = t1177;
        var t285 = t551;
        var t1179 = new SPOCK.Pair(t284, t285);
        var t550 = t1179;
        var t1180 = SPOCK.intern("continuations");
        return ___put_21(k548, t283, t1180, t550);
       };
       var t1182 = SPOCK.intern("continuations");
       return ___get(t1176, t283, t1182);
      };
      return ___print(t1175, "putting ", t283, ": ", t282, " into ", t553);
     };
     var t1185 = SPOCK.intern("continuations");
     return ___get(t1174, t283, t1185);
    };
    return ___map(t1163, t1173, t554);
   };
   var t1188 = SPOCK.intern("messages");
   var t1189 = SPOCK.intern("count");
   return ____25list(t1162, t1188, t1189);
  };
  return ___call_2fcc(t1106, t1161);
 };
 ___map_2drender3 = t1104;	// set! map-render3
 var t1192 = function (k556, t300) {	// map-messages
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1193 = null;
  var t301 = t1193;
  var t1194 = function (t557) {
   var t302 = t557;
   var t1195 = function (t592) {
    t301 = t592;	// set! t301
    var t558 = undefined;
    var t1196 = function (t560) {
     var t310 = t560;
     var t1197 = function (t561) {
      var t311 = t561;
      var t1198 = t300.cloneNode(false);
      var t312 = t1198;
      var t1199 = function (t562) {
       var t1200 = function (t559) {
        return ___yield(k556);
       };
       var t1202 = function (k563, t313) {
        var r = SPOCK.count(arguments);
        if(r) return r;
        var t314 = t313;
        var t1203 = function (t591) {
         var t1204 = function (t590) {
          var t317 = t590;
          var t589 = t317;
          var t1205 = function (t588) {
           var t1206 = function (t587) {
            var t316 = t587;
            var t586 = t316;
            var t1207 = function (t567) {
             var t1208 = function (t585) {
              var t1209 = function (t584) {
               var t318 = t584;
               var t583 = t318;
               var t1210 = function (t568) {
                var t1211 = function (t582) {
                 var t1212 = function (t581) {
                  var t319 = t581;
                  var t580 = t319;
                  var t1213 = function (t569) {
                   var t1214 = function (t579) {
                    var t1215 = function (t578) {
                     var t321 = t578;
                     var t577 = t321;
                     var t1216 = function (t574) {
                      var t1217 = function (t573) {
                       var t1218 = function (t572) {
                        var t320 = t572;
                        var t571 = t320;
                        var t1219 = function (t570) {
                         var t1220 = function (t566) {
                          var t315 = t566;
                          var t565 = t315;
                          var t1221 = function (t564) {
                           return ___node_2dappend_2dchild(k563, t300, t564);
                          };
                          return ___new_2delement(t1221, "div", t565, "class");
                         };
                         return ____25list(t1220, t567, t568, t569, t570);
                        };
                        return ___new_2delement(t1219, "div", t571, "class");
                       };
                       return ____25list(t1218, t573);
                      };
                      var t1227 = function (k575) {	// t322
                       var t1228 = function (t576) {
                        var t1229 = new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("status"), "reloading"), null);
                        return k575(t1229);
                       };
                       return ___print(t1228, "yay ", t314);
                      };
                      var t322 = t1227;
                      var t1232 = SPOCK.callback(t322);
                      return ___set_2dclick(t1217, t574, t1232);
                     };
                     return ___new_2delement(t1216, "button", t577, "class");
                    };
                    return ____25list(t1215, t579);
                   };
                   return ____3ctext_3e(t1214, "click me");
                  };
                  return ___new_2delement(t1213, "div", t580, "class");
                 };
                 return ____25list(t1212, t582);
                };
                return ____3ctext_3e(t1211, t311);
               };
               return ___new_2delement(t1210, "div", t583, "class");
              };
              return ____25list(t1209, t585);
             };
             return ____3ctext_3e(t1208, " ducks", t311);
            };
            return ___new_2delement(t1207, "div", t586, "class");
           };
           return ____25list(t1206, t588);
          };
          return ___new_2delement(t1205, "b", t589, "class");
         };
         return ____25list(t1204, t591);
        };
        return ____3ctext_3e(t1203, t314);
       };
       return ___for_2deach(t1200, t1202, t310);
      };
      return ___remove_2dall_2dchildren(t1199, t300);
     };
     var t1250 = SPOCK.intern("count");
     return ___assoc_2dval(t1197, t1250, t301);
    };
    var t1252 = SPOCK.intern("messages");
    return ___assoc_2dval(t1196, t1252, t301);
   };
   return ___merge_2dbindings(t1195, t302, t301);
  };
  var t1255 = function (k593, t303) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1256 = function (t605) {
    var t308 = t605;
    var t604 = t308;
    var t1257 = function (t594) {
     var t1258 = function (t596) {
      var t1259 = function (t597) {
       var t1260 = function (t595) {
        var t309 = t595;
        return k593(t309);
       };
       return ____25list(t1260, t596, t597);
      };
      var t1263 = SPOCK.intern("count");
      return ___assoc(t1259, t1263, ____2ainits_2a);
     };
     var t1265 = SPOCK.intern("messages");
     return ___assoc(t1258, t1265, ____2ainits_2a);
    };
    var t1267 = function (k598, t304) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1268 = function (t603) {
      var t1269 = function (t599) {
       var t305 = t303;
       var t1270 = function (t602) {
        var t307 = t602;
        var t1271;
        if(t307 !== false) {
         t1271 = t307;
        }
        else {
         var t1272 = null;
         t1271 = t1272;
        }
        var t601 = t1271;
        var t306 = t601;
        var t1273 = new SPOCK.Pair(t305, t306);
        var t600 = t1273;
        var t1274 = SPOCK.intern("continuations");
        return ___put_21(k598, t304, t1274, t600);
       };
       var t1276 = SPOCK.intern("continuations");
       return ___get(t1270, t304, t1276);
      };
      return ___print(t1269, "putting ", t304, ": ", t303, " into ", t603);
     };
     var t1279 = SPOCK.intern("continuations");
     return ___get(t1268, t304, t1279);
    };
    return ___map(t1257, t1267, t604);
   };
   var t1282 = SPOCK.intern("messages");
   var t1283 = SPOCK.intern("count");
   return ____25list(t1256, t1282, t1283);
  };
  return ___call_2fcc(t1194, t1255);
 };
 ___map_2dmessages = t1192;	// set! map-messages
 return ___register_2dcallback(k508, "map-messages", ___map_2dmessages);
};
SPOCK.run(t1103);
var t1287 = function (k606) {
 var t1288 = new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("status"), "Not loaded yet."), new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("messages"), new SPOCK.Pair(8, null)), new SPOCK.Pair(new SPOCK.Pair(SPOCK.intern("count"), 20), null)));
 return ___init(k606, t1288);
};
SPOCK.run(t1287);
SPOCK.flush();
/* END OF GENERATED CODE */
