/* CODE GENERATED BY SPOCK 0 */
var t908 = function (k496) {
 var t909 = function (k497, t1, t2) {	// string-split
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t3 = undefined;
  var t910 = function (k498, t4, t5) {	// t3
   var r = SPOCK.count(arguments);
   if(r) return r;
   loop: while(true) {
    var t6 = t4;
    var t7 = t6;
    var t912 = null;
    var t8 = t912;
    var t913 = (t7) === (t8);
    var t911;
    if(t913 !== false) {
     t911 = t5;
    }
    else {
     var t9 = t4;
     var t10 = t5;
     var t914 = new SPOCK.Pair(t9, t10);
     t911 = t914;
    }
    return k498(t911);
   }
  };
  t3 = t910;	// set! t3
  var t916 = function (t505) {
   var t11 = undefined;
   var t917 = function (k499, t12, t13, t14) {	// t11
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t15 = t14;
    var t16 = t15;
    var t919 = null;
    var t17 = t919;
    var t920 = (t16) === (t17);
    var t918;
    if(t920 !== false) {
     var t921 = function (t502) {
      var t922 = function (t501) {
       var t923 = function (t500) {
        return ___reverse(k499, t500);
       };
       return ___map(t923, ___list_2d_3estring, t501);
      };
      return t3(t922, t502, t13);
     };
     return ___reverse(t921, t12);
    }
    else {
     var t18 = t2;
     var t20 = t14;
     var t21 = t20;
     var t929 = t21.car;
     var t19 = t929;
     var t930 = SPOCK.eqvp(t18, t19);
     var t928;
     if(t930 !== false) {
      var t931 = function (t504) {
       var t932 = function (t503) {
        var t933 = null;
        var t22 = t14;
        var t23 = t22;
        var t934 = t23.cdr;
        return t11(k499, t933, t503, t934);
       };
       return t3(t932, t504, t13);
      };
      return ___reverse(t931, t12);
     }
     else {
      var t26 = t14;
      var t27 = t26;
      var t938 = t27.car;
      var t24 = t938;
      var t25 = t12;
      var t939 = new SPOCK.Pair(t24, t25);
      var t28 = t14;
      var t29 = t28;
      var t940 = t29.cdr;
      return t11(k499, t939, t13, t940);
     }
     t918 = t928;
    }
   };
   t11 = t917;	// set! t11
   var t942 = null;
   var t943 = null;
   return t11(k497, t942, t943, t505);
  };
  return ___string_2d_3elist(t916, t1);
 };
 ___string_2dsplit = t909;	// set! string-split
 var t946 = function (k506, t30, t31) {	// qsa
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t947 = t30.querySelectorAll(t31);
   return k506(t947);
  }
 };
 ___qsa = t946;	// set! qsa
 var t949 = function (k507, t32, t33) {	// qs
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t950 = t32.querySelector(t33);
   return k507(t950);
  }
 };
 ___qs = t949;	// set! qs
 var t952 = function (k508, t34, t35) {	// dqsa
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t953 = document.body.querySelectorAll(t35);
   return k508(t953);
  }
 };
 ___dqsa = t952;	// set! dqsa
 var t955 = function (k509, t36, t37) {	// dqs
  var r = SPOCK.count(arguments);
  if(r) return r;
  return ___qs(k509, document.body, t37);
 };
 ___dqs = t955;	// set! dqs
 var t957 = function (k510, t38) {	// log
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t958 = console.log(t38);
   return k510(t958);
  }
 };
 ___log = t957;	// set! log
 var t960 = function (k511, t39) {	// alert
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t961 = window.alert(t39);
   return k511(t961);
  }
 };
 ___alert = t960;	// set! alert
 var t963 = function (k512, t40) {	// get-id
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t964 = document.getElementById(t40);
   return k512(t964);
  }
 };
 ___get_2did = t963;	// set! get-id
 var t966 = function (k513, t41) {	// remove-node
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t967 = function(k968, x) { return k968(x.parentNode); }
  var t969 = function (t514) {
   var t970 = t514.removeChild(t41);
   return k513(t970);
  };
  return t967(t969, t41);
 };
 ___remove_2dnode = t966;	// set! remove-node
 var t973 = function (k515, t42, t43) {	// insert-node-before
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t974 = function(k975, x) { return k975(x.parentNode); }
  var t976 = function (t516) {
   var t977 = t516.insertBefore(t42, t43);
   return k515(t977);
  };
  return t974(t976, t43);
 };
 ___insert_2dnode_2dbefore = t973;	// set! insert-node-before
 var t980 = function (k517, t44, t45) {	// replace-node
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t981 = function(k982, x) { return k982(x.parentNode); }
  var t983 = function (t518) {
   var t984 = t518.replaceChild(t44, t45);
   return k517(t984);
  };
  return t981(t983, t45);
 };
 ___replace_2dnode = t980;	// set! replace-node
 var t987 = function (k519, t46, t47) {	// node-append-child
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t988 = t46.appendChild(t47);
   return k519(t988);
  }
 };
 ___node_2dappend_2dchild = t987;	// set! node-append-child
 var t990 = function (k520, t48, t49) {	// set-html
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t48.innerHTML = t49;
   return k520(t49);
  }
 };
 ___set_2dhtml = t990;	// set! set-html
 var t992 = function (k521) {	// spock-elements
  loop: while(true) {
   var t994 = document.body.querySelectorAll("*[spock]");
   var t993 = Array.prototype.slice.call(t994);
   return k521(t993);
  }
 };
 ___spock_2delements = t992;	// set! spock-elements
 var t996 = function (k522, t50, t51, t52) {	// add-event-listener
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t997 = t51.addEventListener(t50, t52);
   return k522(t997);
  }
 };
 ___add_2devent_2dlistener = t996;	// set! add-event-listener
 var t999 = function (k523, t53, t54, t55) {	// set-event
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t54.event = t55;
   return k523(t54);
  }
 };
 ___set_2devent = t999;	// set! set-event
 var t1001 = function (k524, t56, t57) {	// set-click
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t56.onclick = t57;
   return k524(t56);
  }
 };
 ___set_2dclick = t1001;	// set! set-click
 var t1003 = function (k525, t58, t59) {	// set-change
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t58.onchange = t59;
   return k525(t58);
  }
 };
 ___set_2dchange = t1003;	// set! set-change
 var t1005 = function (k526, t60, t61) {	// set-input
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   t60.oninput = t61;
   return k526(t60);
  }
 };
 ___set_2dinput = t1005;	// set! set-input
 var t1007 = function (k527, t62) {	// slice
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t1008 = Array.prototype.slice.call(t62);
   return k527(t1008);
  }
 };
 ___slice = t1007;	// set! slice
 var t1010 = function (k528, t63) {	// children
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1011 = t63.childNodes;
  return ___slice(k528, t1011);
 };
 ___children = t1010;	// set! children
 var t1013 = function (k529, t64) {	// car-safe
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t65 = t64;
   var t1015 = (t65) instanceof SPOCK.Pair ;
   var t1014;
   if(t1015 !== false) {
    var t66 = t64;
    var t67 = t66;
    var t1016 = t67.car;
    t1014 = t1016;
   }
   else {
    t1014 = false;
   }
   return k529(t1014);
  }
 };
 ___car_2dsafe = t1013;	// set! car-safe
 var t1018 = function (k530, t68) {	// cdr-safe
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t69 = t68;
   var t1020 = (t69) instanceof SPOCK.Pair ;
   var t1019;
   if(t1020 !== false) {
    var t70 = t68;
    var t71 = t70;
    var t1021 = t71.cdr;
    t1019 = t1021;
   }
   else {
    t1019 = false;
   }
   return k530(t1019);
  }
 };
 ___cdr_2dsafe = t1018;	// set! cdr-safe
 var t1023 = function (k531, t72) {	// empty?
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t74 = t72;
   var t1025 = t74 === undefined;
   var t1024;
   if(t1025 !== false) {
    var t75 = t72;
    var t76 = t75;
    var t1027 = null;
    var t77 = t1027;
    var t1028 = (t76) === (t77);
    var t1026;
    if(t1028 !== false) {
     var t78 = t72;
     var t1029;
     if(t78 !== false) {
      t1029 = false;
     }
     else {
      t1029 = true;
     }
     t1026 = t1029;
    }
    else {
     t1026 = false;
    }
    t1024 = t1026;
   }
   else {
    t1024 = false;
   }
   var t73 = t1024;
   var t1030;
   if(t73 !== false) {
    t1030 = false;
   }
   else {
    t1030 = true;
   }
   return k531(t1030);
  }
 };
 ___empty_3f = t1023;	// set! empty?
 var t1032 = function (k532, t79) {	// nodename
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t1033 = t79.nodeName;
   return k532(t1033);
  }
 };
 ___nodename = t1032;	// set! nodename
 var t1035 = function (k533, t80, t81, t82) {	// h
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1036 = function (t534) {	// t535
   var t83 = t534;
   var t1037 = snabbdom.h(t80, t81, t83);
   return k533(t1037);
  };
  var t535 = t1036;
  var t1039 = function (t536) {
   var t1040;
   if(t536 !== false) {
    return ___list_2d_3evector(t535, t82);
   }
   else {
    var t85 = t82;
    var t1043 = (t85) instanceof Array ;
    var t84 = t1043;
    var t1044;
    if(t84 !== false) {
     t1044 = t84;
    }
    else {
     var t86 = t82;
     var t1045 = typeof(t86);
     var t88 = t1045;
     var t89 = "string";
     var t1046 = (t88) === (t89);
     var t87 = t1046;
     var t1047;
     if(t87 !== false) {
      t1047 = t87;
     }
     else {
      var t1048 = (t86) instanceof SPOCK.String ;
      t1047 = t1048;
     }
     t1044 = t1047;
    }
    var t1042;
    if(t1044 !== false) {
     t1042 = t82;
    }
    else {
     t1042 = false;
    }
    return t535(t1042);
   }
  };
  return ___list_3f(t1039, t82);
 };
 ___h = t1035;	// set! h
 var t1051 = function (k537, t90, t91) {	// patch
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t1052 = patch(t90, t91);
   return k537(t1052);
  }
 };
 ___patch = t1051;	// set! patch
 var t1054 = function (k538, t92, t93, t94) {	// a-click
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1055 = function (t543) {
   var t1056 = function (t539) {
    var t1057 = function (t541) {
     var t1058 = function (t542) {
      var t1059 = function (t540) {
       return ___h(k538, t539, t540, t93);
      };
      return ____25(t1059, "props", t541, "on", t542);
     };
     var t96 = t94;
     var t1062 = SPOCK.callback(t96);
     return ____25(t1058, "click", t1062);
    };
    return ____25(t1057, "href", "#");
   };
   return ___jstring(t1056, t543);
  };
  var t95 = t92;
  var t1066;
  if(t95 !== false) {
   t1066 = t95;
  }
  else {
   t1066 = "";
  }
  return ___string_2dappend(t1055, "a", t1066);
 };
 ___a_2dclick = t1054;	// set! a-click
 var t1068 = function (k544, t97) {	// ajax-cb
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1069 = function(k1070, x) { return k1070(x.responseText); }
  var t1071 = function (t545) {
   return ___log(k544, t545);
  };
  return t1069(t1071, t97);
 };
 ___ajax_2dcb = t1068;	// set! ajax-cb
 var t1074 = function (k546, t98, t99, t100) {	// ajax
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1075 = new XMLHttpRequest();
  var t101 = t1075;
  var t1076 = function (t552) {
   var t102 = t98;
   var t1078 = t102.name;
   var t1077 = t101.open(t1078, t552, true);
   var t547 = t1077;
   var t1079 = function (k548, t104) {	// t103
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t1080 = function(k1081, x) { return k1081(x.status); }
    var t1082 = function (t551) {
     var t105 = t551;
     var t106 = 200;
     var t1083 = SPOCK.equalp(t105, t106);
     var t549 = t1083;
     var t1084;
     if(t549 !== false) {
      return t100(k548, t104);
     }
     else {
      var t1086 = function (t550) {
       return ___log(k548, ___event);
      };
      return ___log(t1086, "Ajax error");
     }
    };
    return t1080(t1082, t101);
   };
   var t103 = t1079;
   var t1090 = SPOCK.callback(t103);
   t101.onload = t1090;
   t101.responseType = "json";
   var t1091 = t101.send();
   return k546(t1091);
  };
  return ___jstring(t1076, t99);
 };
 ___ajax = t1074;	// set! ajax
 var t1094 = function (k553, t107) {	// get-callback
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1095 = function (t554) {	// t555
   var t108 = t554;
   var t1096 = SPOCK.intern("callback");
   return ___get(k553, t108, t1096);
  };
  var t555 = t1095;
  var t109 = t107;
  var t1099 = typeof(t109);
  var t111 = t1099;
  var t112 = "string";
  var t1100 = (t111) === (t112);
  var t110 = t1100;
  var t1101;
  if(t110 !== false) {
   t1101 = t110;
  }
  else {
   var t1102 = (t109) instanceof SPOCK.String ;
   t1101 = t1102;
  }
  var t1098;
  if(t1101 !== false) {
   return ___string_2d_3esymbol(t555, t107);
  }
  else {
   return t555(t107);
  }
 };
 ___get_2dcallback = t1094;	// set! get-callback
 var t1105 = function (k556) {	// waiting
  loop: while(true) {
   return k556(false);
  }
 };
 ___waiting = t1105;	// set! waiting
 ___call_2fcc = ___call_2dwith_2dcurrent_2dcontinuation;	// set! call/cc
 var t1107 = null;
 ____2aqueue_2a = t1107;	// set! *queue*
 var t1108 = function (k557, t113) {	// *enqueue*
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1109 = function (t560) {
   var t114 = t560;
   var t559 = t114;
   var t1110 = function (t558) {
    ____2aqueue_2a = t558;	// set! *queue*
    return k557(undefined);
   };
   return ___append(t1110, ____2aqueue_2a, t559);
  };
  return ____25list(t1109, t113);
 };
 ____2aenqueue_2a = t1108;	// set! *enqueue*
 var t1114 = function (k561) {	// *dequeue*
  loop: while(true) {
   var t116 = ____2aqueue_2a;
   var t117 = t116;
   var t1115 = t117.car;
   var t115 = t1115;
   var t118 = ____2aqueue_2a;
   var t119 = t118;
   var t1116 = t119.cdr;
   ____2aqueue_2a = t1116;	// set! *queue*
   return k561(t115);
  }
 };
 ____2adequeue_2a = t1114;	// set! *dequeue*
 var t1118 = function (k562) {	// yield
  var t120 = ____2aqueue_2a;
  var t121 = t120;
  var t1120 = null;
  var t122 = t1120;
  var t1121 = (t121) === (t122);
  var t1119;
  if(t1121 !== false) {
   return ___waiting(k562);
  }
  else {
   var t1123 = function (t563) {
    var t123 = t563;
    var t1124 = function (t564) {
     return t564(k562);
    };
    return t123(t1124);
   };
   return ____2adequeue_2a(t1123);
  }
 };
 ___yield = t1118;	// set! yield
 var t1128 = function (k565, t124, t125) {	// alist-ref
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1129 = function (t566) {
   return ___cdr_2dsafe(k565, t566);
  };
  return ___assoc(t1129, t124, t125);
 };
 ___alist_2dref = t1128;	// set! alist-ref
 ___merge_2dbindings = ___append;	// set! merge-bindings
 var t1132 = function (k567, t126, t127, t128) {	// put-cons!
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t129 = t128;
  var t1133 = function (t570) {
   var t131 = t570;
   var t1134;
   if(t131 !== false) {
    t1134 = t131;
   }
   else {
    var t1135 = null;
    t1134 = t1135;
   }
   var t569 = t1134;
   var t130 = t569;
   var t1136 = new SPOCK.Pair(t129, t130);
   var t568 = t1136;
   return ___put_21(k567, t126, t127, t568);
  };
  return ___get(t1133, t126, t127);
 };
 ___put_2dcons_21 = t1132;	// set! put-cons!
 var t1139 = function (k571, t132, t133) {	// get-binding
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1140 = function (t572) {
   var t134 = t572;
   var t1141;
   if(t134 !== false) {
    var t135 = t134;
    var t136 = t135;
    var t1142 = t136.cdr;
    t1141 = t1142;
   }
   else {
    t1141 = false;
   }
   return k571(t1141);
  };
  return ___assoc(t1140, t132, t133);
 };
 ___get_2dbinding = t1139;	// set! get-binding
 var t1145 = function (k573, t137, t138) {	// send-bindings
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1146 = function (t574) {
   return t574(k573, t138);
  };
  var t1148 = SPOCK.intern("continuations");
  return ___get(t1146, t137, t1148);
 };
 ___send_2dbindings = t1145;	// set! send-bindings
 var t1150 = function (k575, t139, t140) {	// three-way-split
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t141 = undefined;
  var t1151 = function (k576, t142, t143, t144, t145, t146) {	// t141
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t147 = t143;
   var t148 = t147;
   var t1153 = null;
   var t149 = t1153;
   var t1154 = (t148) === (t149);
   var t1152;
   if(t1154 !== false) {
    var t1155 = function (t578) {
     var t1156 = function (t577) {
      var t150 = t577;
      return k576(t150);
     };
     return ____25list(t1156, t578, t145, t146);
    };
    return ___append(t1155, t142, t144);
   }
   else {
    var t152 = t143;
    var t153 = t152;
    var t1160 = t153.car;
    var t151 = t1160;
    var t154 = undefined;
    var t1161 = function (k579, t155, t156) {	// t154
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t157 = t155;
     var t158 = t157;
     var t1163 = null;
     var t159 = t1163;
     var t1164 = (t158) === (t159);
     var t1162;
     if(t1164 !== false) {
      var t160 = t143;
      var t161 = t160;
      var t1165 = t161.cdr;
      var t162 = t151;
      var t163 = t146;
      var t1166 = new SPOCK.Pair(t162, t163);
      return t141(k579, t156, t1165, t144, t145, t1166);
     }
     else {
      var t165 = t155;
      var t166 = t165;
      var t1168 = t166.car;
      var t164 = t1168;
      var t167 = t151;
      var t168 = t164;
      var t1170 = SPOCK.equalp(t167, t168);
      var t1169;
      if(t1170 !== false) {
       var t1171 = function (t580) {
        var t171 = t143;
        var t172 = t171;
        var t1172 = t172.cdr;
        var t173 = t151;
        var t174 = t145;
        var t1173 = new SPOCK.Pair(t173, t174);
        return t141(k579, t580, t1172, t144, t1173, t146);
       };
       var t169 = t155;
       var t170 = t169;
       var t1175 = t170.cdr;
       return ___append(t1171, t156, t1175);
      }
      else {
       var t175 = t155;
       var t176 = t175;
       var t1177 = t176.cdr;
       var t177 = t164;
       var t178 = t156;
       var t1178 = new SPOCK.Pair(t177, t178);
       return t154(k579, t1177, t1178);
      }
      t1162 = t1169;
     }
    };
    t154 = t1161;	// set! t154
    var t1180 = null;
    return t154(k576, t142, t1180);
   }
  };
  t141 = t1151;	// set! t141
  var t1182 = null;
  var t1183 = null;
  var t1184 = null;
  return t141(k575, t139, t140, t1182, t1183, t1184);
 };
 ___three_2dway_2dsplit = t1150;	// set! three-way-split
 var t1186 = function (k581, t179, t180) {	// merge-alist-sets
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t182 = t180;
  var t183 = t182;
  var t1187 = t183.car;
  var t181 = t1187;
  var t184 = undefined;
  var t1188 = function (k582, t185, t186, t187) {	// t184
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t189 = t186;
   var t190 = t189;
   var t1190 = null;
   var t191 = t1190;
   var t1191 = (t190) === (t191);
   var t188 = t1191;
   var t1192;
   if(t188 !== false) {
    t1192 = t188;
   }
   else {
    var t192 = t185;
    var t193 = t192;
    var t1193 = null;
    var t194 = t1193;
    var t1194 = (t193) === (t194);
    t1192 = t1194;
   }
   var t1189;
   if(t1192 !== false) {
    var t1195 = function (t585) {
     var t199 = t585;
     var t584 = t199;
     var t197 = t584;
     var t198 = t186;
     var t1196 = new SPOCK.Pair(t197, t198);
     var t583 = t1196;
     var t195 = t583;
     var t196 = t187;
     var t1197 = new SPOCK.Pair(t195, t196);
     return k582(t1197);
    };
    return ____25list(t1195, t181);
   }
   else {
    var t201 = t185;
    var t203 = t201;
    var t204 = t203;
    var t1200 = t204.car;
    var t202 = t1200;
    var t205 = t202;
    var t1201 = t205.car;
    var t200 = t1201;
    var t207 = t185;
    var t209 = t207;
    var t210 = t209;
    var t1202 = t210.car;
    var t208 = t1202;
    var t211 = t208;
    var t1203 = t211.cdr;
    var t206 = t1203;
    var t1204 = function (t586) {
     var t212 = t586;
     var t214 = t212;
     var t215 = t214;
     var t1205 = t215.car;
     var t213 = t1205;
     var t217 = t212;
     var t219 = t217;
     var t220 = t219;
     var t1206 = t220.cdr;
     var t218 = t1206;
     var t221 = t218;
     var t1207 = t221.car;
     var t216 = t1207;
     var t1208 = function (t587) {
      var t222 = t587;
      var t1209 = function (t590) {
       var t225 = t590;
       var t589 = t225;
       var t1210 = function (t588) {
        var t223 = t185;
        var t224 = t223;
        var t1211 = t224.cdr;
        return t184(k582, t1211, t222, t588);
       };
       return ___append(t1210, t589, t187);
      };
      var t226 = t200;
      var t227 = t213;
      var t1214 = new SPOCK.Pair(t226, t227);
      var t230 = t181;
      var t231 = t200;
      var t1215 = new SPOCK.Pair(t230, t231);
      var t228 = t1215;
      var t229 = t216;
      var t1216 = new SPOCK.Pair(t228, t229);
      return ____25list(t1209, t1214, t1216);
     };
     return ___caddr(t1208, t212);
    };
    return ___three_2dway_2dsplit(t1204, t206, t186);
   }
  };
  t184 = t1188;	// set! t184
  var t232 = t180;
  var t233 = t232;
  var t1220 = t233.cdr;
  var t1221 = null;
  return t184(k581, t179, t1220, t1221);
 };
 ___merge_2dalist_2dsets = t1186;	// set! merge-alist-sets
 var t1223 = function (k591, t234) {	// merge-continuation-lists
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t235 = undefined;
  var t1224 = function (k592, t236, t237) {	// t235
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t238 = t237;
   var t239 = t238;
   var t1226 = null;
   var t240 = t1226;
   var t1227 = (t239) === (t240);
   var t1225;
   if(t1227 !== false) {
    return k592(t236);
   }
   else {
    var t1229 = function (t593) {
     var t243 = t237;
     var t244 = t243;
     var t1230 = t244.cdr;
     return t235(k592, t593, t1230);
    };
    var t241 = t237;
    var t242 = t241;
    var t1232 = t242.car;
    return ___merge_2dalist_2dsets(t1229, t236, t1232);
   }
  };
  t235 = t1224;	// set! t235
  var t1234 = null;
  return t235(k591, t1234, t234);
 };
 ___merge_2dcontinuation_2dlists = t1223;	// set! merge-continuation-lists
 var t1236 = function (k594, t245) {	// send-vars
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1237 = function (t600) {
   var t1238 = function (t599) {
    var t1239 = function (t595) {
     return ___yield(k594);
    };
    var t1241 = function (k596, t246) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t249 = t246;
     var t250 = t249;
     var t1242 = t250.car;
     var t247 = t1242;
     var t251 = t246;
     var t252 = t251;
     var t1243 = t252.cdr;
     var t248 = t1243;
     var t254 = t248;
     var t255 = t254;
     var t1245 = null;
     var t256 = t1245;
     var t1246 = (t255) === (t256);
     var t253 = t1246;
     var t1247;
     if(t253 !== false) {
      t1247 = false;
     }
     else {
      t1247 = true;
     }
     var t1244;
     if(t1247 !== false) {
      var t1248 = function (k597, t257) {
       var r = SPOCK.count(arguments);
       if(r) return r;
       var t1249 = function (k598) {
        return t257(k598, t245);
       };
       return ____2aenqueue_2a(k597, t1249);
      };
      return ___map(k596, t1248, t248);
     }
     else {
      return k596(undefined);
     }
    };
    return ___map(t1239, t1241, t599);
   };
   return ___merge_2dcontinuation_2dlists(t1238, t600);
  };
  var t1256 = function (k601, t258) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t260 = t258;
   var t261 = t260;
   var t1257 = t261.car;
   var t259 = t1257;
   var t262 = t259;
   var t1258 = function (t602) {
    var t263 = t602;
    var t1259 = new SPOCK.Pair(t262, t263);
    return k601(t1259);
   };
   var t1261 = SPOCK.intern("continuations");
   return ___get(t1258, t259, t1261);
  };
  return ___map(t1237, t1256, t245);
 };
 ___send_2dvars = t1236;	// set! send-vars
 var t1264 = function (k603) {	// get-hash
  loop: while(true) {
   var t264 = window.location.hash;
   var t1265;
   if(t264 !== false) {
    var t266 = t264;
    var t267 = "";
    var t1267 = SPOCK.equalp(t266, t267);
    var t265 = t1267;
    var t1268;
    if(t265 !== false) {
     t1268 = false;
    }
    else {
     t1268 = true;
    }
    var t1266;
    if(t1268 !== false) {
     var t269 = t264;
     var t270 = "#";
     var t1270 = SPOCK.equalp(t269, t270);
     var t268 = t1270;
     var t1271;
     if(t268 !== false) {
      t1271 = false;
     }
     else {
      t1271 = true;
     }
     var t1269;
     if(t1271 !== false) {
      var t271 = t264;
      var t272 = 1;
      var t273 = undefined;
      var t275 = t271;
      var t1272 = SPOCK.jstring(t275);
      var t274 = t1272;
      var t276 = t273;
      var t1275 = t276 === undefined;
      var t1274;
      if(t1275 !== false) {
       var t1276 = t274.length;
       t1274 = t1276;
      }
      else {
       t1274 = t273;
      }
      var t1273 = t274.substring(t272, t1274);
      t1269 = t1273;
     }
     else {
      t1269 = false;
     }
     t1266 = t1269;
    }
    else {
     t1266 = false;
    }
    t1265 = t1266;
   }
   else {
    t1265 = false;
   }
   return k603(t1265);
  }
 };
 ___get_2dhash = t1264;	// set! get-hash
 var t1278 = function (k604, t277) {	// set-hash!
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1279 = function (t606) {
   var t1280 = function (t605) {
    window.location.hash = t605
    return k604(undefined);
   };
   return ___jstring(t1280, t606);
  };
  return ___string_2dappend(t1279, "#", t277);
 };
 ___set_2dhash_21 = t1278;	// set! set-hash!
 var t1284 = function (k607) {	// get-path
  var t1285 = new SPOCK.Char("/");
  return ___string_2dsplit(k607, window.location.pathname, t1285);
 };
 ___get_2dpath = t1284;	// set! get-path
 var t1287 = function (k608, t278, t279) {	// register-component
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1288 = function (t609) {	// t610
   var t280 = t609;
   var t1289 = SPOCK.intern("callback");
   return ___put_21(k608, t280, t1289, t279);
  };
  var t610 = t1288;
  var t281 = t278;
  var t1292 = typeof(t281);
  var t283 = t1292;
  var t284 = "string";
  var t1293 = (t283) === (t284);
  var t282 = t1293;
  var t1294;
  if(t282 !== false) {
   t1294 = t282;
  }
  else {
   var t1295 = (t281) instanceof SPOCK.String ;
   t1294 = t1295;
  }
  var t1291;
  if(t1294 !== false) {
   return ___string_2d_3esymbol(t610, t278);
  }
  else {
   return t610(t278);
  }
 };
 ___register_2dcomponent = t1287;	// set! register-component
 var t1298 = function (k611) {	// start
  var t1299 = function (t612) {
   return ___print(k611, "waiting...");
  };
  var t1301 = function (k613, t285) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   loop: while(true) {
    ___waiting = t285;	// set! waiting
    return k613(undefined);
   }
  };
  return ___call_2fcc(t1299, t1301);
 };
 ___start = t1298;	// set! start
 var t1304 = function (k614, t286, t287) {	// github-api-call
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1305 = SPOCK.intern("GET");
  var t1306 = function (k615, t288) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1307 = function(k1308, x) { return k1308(x.currentTarget); }
   var t1309 = function (t617) {
    var t1310 = function(k1311, x) { return k1311(x.response); }
    var t1312 = function (t616) {
     return t287(k615, t616);
    };
    return t1310(t1312, t617);
   };
   return t1307(t1309, t288);
  };
  return ___ajax(k614, t1305, t286, t1306);
 };
 ___github_2dapi_2dcall = t1304;	// set! github-api-call
 var t1317 = function (k618, t289, t290) {	// github-api-repos
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1318 = function (t619) {
   return ___github_2dapi_2dcall(k618, t619, t290);
  };
  return ___string_2dappend(t1318, "https://api.github.com/users/", t289, "/repos");
 };
 ___github_2dapi_2drepos = t1317;	// set! github-api-repos
 var t1321 = function (k620, t291, t292, t293) {	// github-api-repo
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1322 = function (t621) {
   return ___github_2dapi_2dcall(k620, t621, t293);
  };
  return ___string_2dappend(t1322, "https://api.github.com/repos/", t291, "/", t292, "/contents");
 };
 ___github_2dapi_2drepo = t1321;	// set! github-api-repo
 var t1325 = function (t622) {
  ___top_2dnode = t622;	// set! top-node
  return k496(undefined);
 };
 return ____25(t1325, "path", "");
};
SPOCK.run(t908);
var t1328 = function (k623) {
 var t1329 = function (k624, t294, t295) {	// make-tree
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t296 = t294;
   var t297 = t295;
   var t1330 = new SPOCK.Pair(t296, t297);
   return k624(t1330);
  }
 };
 ___make_2dtree = t1329;	// set! make-tree
 var t1332 = function (k625, t298) {	// empty-tree
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1333 = null;
  return ___make_2dtree(k625, t298, t1333);
 };
 ___empty_2dtree = t1332;	// set! empty-tree
 var t1335 = function (k626, t299) {	// tree-obj
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t300 = t299;
   var t301 = t300;
   var t1336 = t301.car;
   return k626(t1336);
  }
 };
 ___tree_2dobj = t1335;	// set! tree-obj
 var t1338 = function (k627, t302) {	// tree-path
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1339 = function (t628) {
   var t1340 = function(k1341, x) { return k1341(x.path); }
   return t1340(k627, t628);
  };
  return ___tree_2dobj(t1339, t302);
 };
 ___tree_2dpath = t1338;	// set! tree-path
 var t1344 = function (k629, t303) {	// tree-children
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t304 = t303;
   var t305 = t304;
   var t1345 = t305.cdr;
   return k629(t1345);
  }
 };
 ___tree_2dchildren = t1344;	// set! tree-children
 var t1347 = function (k630, t306, t307) {	// tree-replace-children
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1348 = function (t631) {
   return ___make_2dtree(k630, t631, t307);
  };
  return ___tree_2dobj(t1348, t306);
 };
 ___tree_2dreplace_2dchildren = t1347;	// set! tree-replace-children
 var t1351 = function (k632, t308, t309) {	// substring=?
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   var t310 = t308;
   var t312 = t309;
   var t313 = 0;
   var t315 = t308;
   var t316 = t315;
   var t1353 = SPOCK.jstring(t316);
   var t1352 = t1353.length;
   var t314 = t1352;
   var t318 = t312;
   var t1354 = SPOCK.jstring(t318);
   var t317 = t1354;
   var t319 = t314;
   var t1357 = t319 === undefined;
   var t1356;
   if(t1357 !== false) {
    var t1358 = t317.length;
    t1356 = t1358;
   }
   else {
    t1356 = t314;
   }
   var t1355 = t317.substring(t313, t1356);
   var t311 = t1355;
   var t1359 = SPOCK.equalp(t310, t311);
   return k632(t1359);
  }
 };
 ___substring_3d_3f = t1351;	// set! substring=?
 var t1361 = function (k633, t320, t321, t322) {	// tree-insert-children
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1362 = function (t642) {
   var t1363 = function (t634) {
    return ___tree_2dreplace_2dchildren(k633, t320, t634);
   };
   var t1365 = function (k635, t323) {
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t1366 = function (t641) {
     var t324 = t641;
     var t325 = t322;
     var t1367 = SPOCK.equalp(t324, t325);
     var t636 = t1367;
     var t1368;
     if(t636 !== false) {
      var t1369 = function (t637) {	// t638
       return ___tree_2dreplace_2dchildren(k635, t323, t637);
      };
      var t638 = t1369;
      var t327 = t321;
      var t1372 = (t327) instanceof SPOCK.Pair ;
      var t326 = t1372;
      var t1373;
      if(t326 !== false) {
       t1373 = t326;
      }
      else {
       var t328 = t321;
       var t1374 = (t328) instanceof Array ;
       t1373 = t1374;
      }
      var t1371;
      if(t1373 !== false) {
       return ___map(t638, ___empty_2dtree, t321);
      }
      else {
       return t638(t321);
      }
      t1368 = t1371;
     }
     else {
      var t1377 = function (t640) {
       var t1378 = function (t639) {
        var t1379;
        if(t639 !== false) {
         return ___tree_2dinsert_2dchildren(k635, t323, t321, t322);
        }
        else {
         return k635(t323);
        }
       };
       return ___substring_3d_3f(t1378, t640, t322);
      };
      return ___tree_2dpath(t1377, t323);
     }
    };
    return ___tree_2dpath(t1366, t323);
   };
   return ___map(t1363, t1365, t642);
  };
  return ___tree_2dchildren(t1362, t320);
 };
 ___tree_2dinsert_2dchildren = t1361;	// set! tree-insert-children
 var t1387 = function (k643, t329, t330) {	// tree-remove-children
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1388 = function (t650) {
   var t1389 = function (t644) {
    return ___tree_2dreplace_2dchildren(k643, t329, t644);
   };
   var t1391 = function (k645, t331) {
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t332 = t330;
    var t1392 = function (t649) {
     var t333 = t649;
     var t1393 = SPOCK.equalp(t332, t333);
     var t646 = t1393;
     var t1394;
     if(t646 !== false) {
      var t1395 = null;
      return ___tree_2dreplace_2dchildren(k645, t331, t1395);
     }
     else {
      var t1397 = function (t648) {
       var t1398 = function (t647) {
        var t1399;
        if(t647 !== false) {
         return ___tree_2dremove_2dchildren(k645, t331, t330);
        }
        else {
         return k645(t331);
        }
       };
       return ___substring_3d_3f(t1398, t648, t330);
      };
      return ___tree_2dpath(t1397, t331);
     }
    };
    return ___tree_2dpath(t1392, t331);
   };
   return ___map(t1389, t1391, t650);
  };
  return ___tree_2dchildren(t1388, t329);
 };
 ___tree_2dremove_2dchildren = t1387;	// set! tree-remove-children
 var t334 = undefined;
 var t1407 = function (t660) {
  t334 = t660;	// set! t334
  var t651 = undefined;
  var t1408 = function (t653) {
   var t340 = t653;
   var t1409 = function (t652) {	// t654
    return ___yield(k623);
   };
   var t654 = t1409;
   var t1411;
   if(t340 !== false) {
    var t1412 = function (k655, t341) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1413 = function (k656) {
      loop: while(true) {
       return k656(t341);
      }
     };
     var t1415 = function (k657, t342) {
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t1416 = function (t659) {
       var t343 = t659;
       var t658 = t343;
       return ___send_2dvars(k657, t658);
      };
      var t1418 = SPOCK.intern("repos");
      var t344 = t1418;
      var t345 = t342;
      var t1419 = new SPOCK.Pair(t344, t345);
      return ____25list(t1416, t1419);
     };
     return ___call_2dwith_2dvalues(k655, t1413, t1415);
    };
    return ___github_2dapi_2drepos(t654, t340, t1412);
   }
   else {
    return t654(undefined);
   }
  };
  var t1424 = SPOCK.intern("user");
  return ___alist_2dref(t1408, t1424, t334);
 };
 var t1426 = function (k661, t335) {
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1427 = function (k663, t337) {	// t336
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1428 = function (t664) {
    return t335(k663, t664);
   };
   return ___append(t1428, t337, t334);
  };
  var t336 = t1427;
  var t1431 = function (t667) {
   var t339 = t667;
   var t666 = t339;
   var t1432 = function (t662) {
    var t1433 = null;
    return k661(t1433);
   };
   var t1435 = function (k665, t338) {
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t1436 = SPOCK.intern("continuations");
    return ___put_2dcons_21(k665, t338, t1436, t336);
   };
   return ___map(t1432, t1435, t666);
  };
  var t1439 = SPOCK.intern("user");
  return ____25list(t1431, t1439);
 };
 return ___call_2fcc(t1407, t1426);
};
SPOCK.run(t1328);
var t1442 = function (k668) {
 var t346 = undefined;
 var t1443 = function (t681) {
  t346 = t681;	// set! t346
  var t669 = undefined;
  var t1444 = function (t671) {
   var t352 = t671;
   var t1445 = function (t672) {
    var t353 = t672;
    var t1446 = function (t670) {	// t673
     return ___yield(k668);
    };
    var t673 = t1446;
    var t1449;
    if(t352 !== false) {
     t1449 = t353;
    }
    else {
     t1449 = false;
    }
    var t1448;
    if(t1449 !== false) {
     var t1450 = function (k674, t354) {
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t1451 = function (t680) {
       var t1452 = function (t675) {
        var t355 = t675;
        var t1453 = function (k676) {
         loop: while(true) {
          return k676(t355);
         }
        };
        var t1455 = function (k677, t356) {
         var r = SPOCK.count(arguments);
         if(r) return r;
         var t1456 = function (t679) {
          var t357 = t679;
          var t678 = t357;
          return ___send_2dvars(k677, t678);
         };
         var t1458 = SPOCK.intern("files");
         var t358 = t1458;
         var t359 = t356;
         var t1459 = new SPOCK.Pair(t358, t359);
         return ____25list(t1456, t1459);
        };
        return ___call_2dwith_2dvalues(k674, t1453, t1455);
       };
       return ___make_2dtree(t1452, ___top_2dnode, t680);
      };
      return ___map(t1451, ___empty_2dtree, t354);
     };
     return ___github_2dapi_2drepo(t673, t352, t353, t1450);
    }
    else {
     return t673(undefined);
    }
   };
   var t1466 = SPOCK.intern("repo");
   return ___alist_2dref(t1445, t1466, t346);
  };
  var t1468 = SPOCK.intern("user");
  return ___alist_2dref(t1444, t1468, t346);
 };
 var t1470 = function (k682, t347) {
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1471 = function (k684, t349) {	// t348
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1472 = function (t685) {
    return t347(k684, t685);
   };
   return ___append(t1472, t349, t346);
  };
  var t348 = t1471;
  var t1475 = function (t688) {
   var t351 = t688;
   var t687 = t351;
   var t1476 = function (t683) {
    var t1477 = null;
    return k682(t1477);
   };
   var t1479 = function (k686, t350) {
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t1480 = SPOCK.intern("continuations");
    return ___put_2dcons_21(k686, t350, t1480, t348);
   };
   return ___map(t1476, t1479, t687);
  };
  var t1483 = SPOCK.intern("user");
  var t1484 = SPOCK.intern("repo");
  return ____25list(t1475, t1483, t1484);
 };
 return ___call_2fcc(t1443, t1470);
};
SPOCK.run(t1442);
var t1487 = function (k689) {
 var t360 = undefined;
 var t1488 = function (t709) {
  t360 = t709;	// set! t360
  var t690 = undefined;
  var t1489 = function (t692) {
   var t366 = t692;
   var t1490 = function (t693) {
    var t367 = t693;
    var t1491 = function (t691) {	// t694
     return ___yield(k689);
    };
    var t694 = t1491;
    var t1493;
    if(t367 !== false) {
     var t1494 = function (k695) {
      var t1495 = function(k1496, x) { return k1496(x.url); }
      var t1497 = function (t699) {
       var t1498 = function (t696) {
        var t1499 = function(k1500, x) { return k1500(x.path); }
        var t1501 = function (t698) {
         var t1502 = function (t697) {
          return ___values(k695, false, t697);
         };
         var t1504 = SPOCK.intern("loading");
         return ___tree_2dinsert_2dchildren(t1502, t366, t1504, t698);
        };
        return t1499(t1501, t367);
       };
       var t1507 = function (k700, t368) {
        var r = SPOCK.count(arguments);
        if(r) return r;
        var t1508 = function (k701) {
         var t1509 = function(k1510, x) { return k1510(x.path); }
         var t1511 = function (t702) {
          return ___tree_2dinsert_2dchildren(k701, t366, t368, t702);
         };
         return t1509(t1511, t367);
        };
        var t1514 = function (k703, t369) {
         var r = SPOCK.count(arguments);
         if(r) return r;
         var t1515 = function (t705) {
          var t370 = t705;
          var t704 = t370;
          return ___send_2dvars(k703, t704);
         };
         var t1517 = SPOCK.intern("files");
         var t371 = t1517;
         var t372 = t369;
         var t1518 = new SPOCK.Pair(t371, t372);
         return ____25list(t1515, t1518);
        };
        return ___call_2dwith_2dvalues(k700, t1508, t1514);
       };
       return ___github_2dapi_2dcall(t1498, t699, t1507);
      };
      return t1495(t1497, t367);
     };
     var t1523 = function (k706, t373, t374) {
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t1524 = function (t708) {
       var t375 = t708;
       var t707 = t375;
       return ___send_2dvars(k706, t707);
      };
      var t1526 = SPOCK.intern("file-to-open");
      var t376 = t1526;
      var t377 = t373;
      var t1527 = new SPOCK.Pair(t376, t377);
      var t1528 = SPOCK.intern("files");
      var t378 = t1528;
      var t379 = t374;
      var t1529 = new SPOCK.Pair(t378, t379);
      return ____25list(t1524, t1527, t1529);
     };
     return ___call_2dwith_2dvalues(t694, t1494, t1523);
    }
    else {
     return t694(undefined);
    }
   };
   var t1533 = SPOCK.intern("file-to-open");
   return ___alist_2dref(t1490, t1533, t360);
  };
  var t1535 = SPOCK.intern("files");
  return ___alist_2dref(t1489, t1535, t360);
 };
 var t1537 = function (k710, t361) {
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1538 = function (k712, t363) {	// t362
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1539 = function (t713) {
    return t361(k712, t713);
   };
   return ___append(t1539, t363, t360);
  };
  var t362 = t1538;
  var t1542 = function (t716) {
   var t365 = t716;
   var t715 = t365;
   var t1543 = function (t711) {
    var t1544 = null;
    return k710(t1544);
   };
   var t1546 = function (k714, t364) {
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t1547 = SPOCK.intern("continuations");
    return ___put_2dcons_21(k714, t364, t1547, t362);
   };
   return ___map(t1543, t1546, t715);
  };
  var t1550 = SPOCK.intern("files");
  var t1551 = SPOCK.intern("file-to-open");
  return ____25list(t1542, t1550, t1551);
 };
 return ___call_2fcc(t1488, t1537);
};
SPOCK.run(t1487);
var t1554 = function (k717) {
 var t380 = undefined;
 var t1555 = function (t729) {
  t380 = t729;	// set! t380
  var t718 = undefined;
  var t1556 = function (t720) {
   var t386 = t720;
   var t1557 = function (t721) {
    var t387 = t721;
    var t1558 = function (t719) {	// t722
     return ___yield(k717);
    };
    var t722 = t1558;
    var t1560;
    if(t387 !== false) {
     var t1561 = function (k723) {
      var t1562 = function(k1563, x) { return k1563(x.path); }
      var t1564 = function (t725) {
       var t1565 = function (t724) {
        return ___values(k723, false, t724);
       };
       return ___tree_2dremove_2dchildren(t1565, t386, t725);
      };
      return t1562(t1564, t387);
     };
     var t1569 = function (k726, t388, t389) {
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t1570 = function (t728) {
       var t390 = t728;
       var t727 = t390;
       return ___send_2dvars(k726, t727);
      };
      var t1572 = SPOCK.intern("file-to-close");
      var t391 = t1572;
      var t392 = t388;
      var t1573 = new SPOCK.Pair(t391, t392);
      var t1574 = SPOCK.intern("files");
      var t393 = t1574;
      var t394 = t389;
      var t1575 = new SPOCK.Pair(t393, t394);
      return ____25list(t1570, t1573, t1575);
     };
     return ___call_2dwith_2dvalues(t722, t1561, t1569);
    }
    else {
     return t722(undefined);
    }
   };
   var t1579 = SPOCK.intern("file-to-close");
   return ___alist_2dref(t1557, t1579, t380);
  };
  var t1581 = SPOCK.intern("files");
  return ___alist_2dref(t1556, t1581, t380);
 };
 var t1583 = function (k730, t381) {
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1584 = function (k732, t383) {	// t382
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1585 = function (t733) {
    return t381(k732, t733);
   };
   return ___append(t1585, t383, t380);
  };
  var t382 = t1584;
  var t1588 = function (t736) {
   var t385 = t736;
   var t735 = t385;
   var t1589 = function (t731) {
    var t1590 = null;
    return k730(t1590);
   };
   var t1592 = function (k734, t384) {
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t1593 = SPOCK.intern("continuations");
    return ___put_2dcons_21(k734, t384, t1593, t382);
   };
   return ___map(t1589, t1592, t735);
  };
  var t1596 = SPOCK.intern("files");
  var t1597 = SPOCK.intern("file-to-close");
  return ____25list(t1588, t1596, t1597);
 };
 return ___call_2fcc(t1555, t1583);
};
SPOCK.run(t1554);
var t1600 = function (k737) {
 var t1601 = function (k738, t395) {
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t396 = t395;
  var t397 = undefined;
  var t1602 = function (t760) {
   t397 = t760;	// set! t397
   var t739 = undefined;
   var t1603 = function (t741) {
    var t403 = t741;
    var t1604 = function (t759) {
     var t1605 = function (t745) {
      var t1606 = function (t748) {
       var t1607 = function (t749) {
        var t1608 = function (t746) {
         var t1609 = function (t747) {
          var t1610 = function (t742) {
           var t404 = t742;
           var t1611 = function (t740) {	// t743
            return ___yield(k738);
           };
           var t743 = t1611;
           var t1613;
           if(t404 !== false) {
            var t1614 = function (t744) {
             t396 = t744;	// set! t396
             return t743(undefined);
            };
            return ___patch(t1614, t396, t404);
           }
           else {
            return t743(t396);
           }
          };
          return ___h(t1610, t745, t746, t747);
         };
         return ___vector(t1609);
        };
        return ____25(t1608, "props", t748, "on", t749);
       };
       var t1621 = function (k750, t408) {	// t407
        var r = SPOCK.count(arguments);
        if(r) return r;
        var t1622 = function(k1623, x) { return k1623(x.target); }
        var t1624 = function (t758) {
         var t1625 = function(k1626, x) { return k1626(x.value); }
         var t1627 = function (t757) {
          var t1628 = function (t751) {
           var t1629 = function (k752) {
            var t1630 = function(k1631, x) { return k1631(x.target); }
            var t1632 = function (t753) {
             var t1633 = function(k1634, x) { return k1634(x.value); }
             return t1633(k752, t753);
            };
            return t1630(t1632, t408);
           };
           var t1637 = function (k754, t409) {
            var r = SPOCK.count(arguments);
            if(r) return r;
            var t1638 = function (t756) {
             var t410 = t756;
             var t755 = t410;
             return ___send_2dvars(k754, t755);
            };
            var t1640 = SPOCK.intern("user");
            var t411 = t1640;
            var t412 = t409;
            var t1641 = new SPOCK.Pair(t411, t412);
            return ____25list(t1638, t1641);
           };
           return ___call_2dwith_2dvalues(k750, t1629, t1637);
          };
          return ___set_2dhash_21(t1628, t757);
         };
         return t1625(t1627, t758);
        };
        return t1622(t1624, t408);
       };
       var t407 = t1621;
       var t1647 = SPOCK.callback(t407);
       return ____25(t1607, "change", t1647);
      };
      var t406 = t403;
      var t1649;
      if(t406 !== false) {
       t1649 = t406;
      }
      else {
       t1649 = "";
      }
      return ____25(t1606, "type", "text", "value", t1649);
     };
     return ___jstring(t1605, t759);
    };
    var t405 = false;
    var t1652;
    if(t405 !== false) {
     t1652 = t405;
    }
    else {
     t1652 = "";
    }
    return ___string_2dappend(t1604, "input", t1652);
   };
   var t1654 = SPOCK.intern("user");
   return ___alist_2dref(t1603, t1654, t397);
  };
  var t1656 = function (k761, t398) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1657 = function (k763, t400) {	// t399
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t1658 = function (t764) {
     return t398(k763, t764);
    };
    return ___append(t1658, t400, t397);
   };
   var t399 = t1657;
   var t1661 = function (t767) {
    var t402 = t767;
    var t766 = t402;
    var t1662 = function (t762) {
     var t1663 = null;
     return k761(t1663);
    };
    var t1665 = function (k765, t401) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1666 = SPOCK.intern("continuations");
     return ___put_2dcons_21(k765, t401, t1666, t399);
    };
    return ___map(t1662, t1665, t766);
   };
   var t1669 = SPOCK.intern("user");
   return ____25list(t1661, t1669);
  };
  return ___call_2fcc(t1602, t1656);
 };
 return ___register_2dcomponent(k737, "change-user", t1601);
};
SPOCK.run(t1600);
var t1673 = function (k768) {
 var t1674 = function (k769, t413) {
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t414 = t413;
  var t415 = undefined;
  var t1675 = function (t799) {
   t415 = t799;	// set! t415
   var t770 = undefined;
   var t1676 = function (t772) {
    var t421 = t772;
    var t1677 = function (t798) {
     var t1678 = function (t776) {
      var t1679 = function (t791) {
       var t1680 = function (t777) {
        var t1681 = function (t790) {
         var t1682 = function (t787) {
          var t1683 = function (t789) {
           var t1684 = function (t788) {
            var t1685 = function (t779) {
             var t430 = t779;
             var t1686 = function (t785) {	// t786
              var t1687 = function (t780) {
               var t431 = t780;
               var t1688 = new SPOCK.Pair(t430, t431);
               var t778 = t1688;
               var t1689 = function (t773) {
                var t422 = t773;
                var t1690 = function (t771) {	// t774
                 return ___yield(k769);
                };
                var t774 = t1690;
                var t1692;
                if(t422 !== false) {
                 var t1693 = function (t775) {
                  t414 = t775;	// set! t414
                  return t774(undefined);
                 };
                 return ___patch(t1693, t414, t422);
                }
                else {
                 return t774(t414);
                }
               };
               return ___h(t1689, t776, t777, t778);
              };
              var t1698 = function (k781, t433) {
               var r = SPOCK.count(arguments);
               if(r) return r;
               var t1699 = function (t784) {
                var t1700 = function (t782) {
                 var t1701 = function(k1702, x) { return k1702(x.name); }
                 var t1703 = function (t783) {
                  return ___h(k781, t782, false, t783);
                 };
                 return t1701(t1703, t433);
                };
                return ___jstring(t1700, t784);
               };
               var t434 = false;
               var t1707;
               if(t434 !== false) {
                t1707 = t434;
               }
               else {
                t1707 = "";
               }
               return ___string_2dappend(t1699, "option", t1707);
              };
              return ___map(t1687, t1698, t785);
             };
             var t786 = t1686;
             var t435 = t421;
             var t1711 = (t435) instanceof Array ;
             var t1710;
             if(t1711 !== false) {
              return ___vector_2d_3elist(t786, t421);
             }
             else {
              return ___vector(t786);
             }
            };
            return ___h(t1685, t787, t788, "----");
           };
           return ____25(t1684, "props", t789);
          };
          return ____25(t1683, "value", false);
         };
         return ___jstring(t1682, t790);
        };
        var t432 = false;
        var t1718;
        if(t432 !== false) {
         t1718 = t432;
        }
        else {
         t1718 = "";
        }
        return ___string_2dappend(t1681, "option", t1718);
       };
       return ____25(t1680, "on", t791);
      };
      var t1721 = function (k792, t425) {	// t424
       var r = SPOCK.count(arguments);
       if(r) return r;
       var t1722 = function (k793) {
        var t1723 = function(k1724, x) { return k1724(x.target); }
        var t1725 = function (t794) {
         var t1726 = function(k1727, x) { return k1727(x.value); }
         return t1726(k793, t794);
        };
        return t1723(t1725, t425);
       };
       var t1730 = function (k795, t426) {
        var r = SPOCK.count(arguments);
        if(r) return r;
        var t1731 = function (t797) {
         var t427 = t797;
         var t796 = t427;
         return ___send_2dvars(k795, t796);
        };
        var t1733 = SPOCK.intern("repo");
        var t428 = t1733;
        var t429 = t426;
        var t1734 = new SPOCK.Pair(t428, t429);
        return ____25list(t1731, t1734);
       };
       return ___call_2dwith_2dvalues(k792, t1722, t1730);
      };
      var t424 = t1721;
      var t1737 = SPOCK.callback(t424);
      return ____25(t1679, "change", t1737);
     };
     return ___jstring(t1678, t798);
    };
    var t423 = false;
    var t1740;
    if(t423 !== false) {
     t1740 = t423;
    }
    else {
     t1740 = "";
    }
    return ___string_2dappend(t1677, "select", t1740);
   };
   var t1742 = SPOCK.intern("repos");
   return ___alist_2dref(t1676, t1742, t415);
  };
  var t1744 = function (k800, t416) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1745 = function (k802, t418) {	// t417
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t1746 = function (t803) {
     return t416(k802, t803);
    };
    return ___append(t1746, t418, t415);
   };
   var t417 = t1745;
   var t1749 = function (t806) {
    var t420 = t806;
    var t805 = t420;
    var t1750 = function (t801) {
     var t1751 = null;
     return k800(t1751);
    };
    var t1753 = function (k804, t419) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1754 = SPOCK.intern("continuations");
     return ___put_2dcons_21(k804, t419, t1754, t417);
    };
    return ___map(t1750, t1753, t805);
   };
   var t1757 = SPOCK.intern("repos");
   return ____25list(t1749, t1757);
  };
  return ___call_2fcc(t1675, t1744);
 };
 return ___register_2dcomponent(k768, "choose-repository", t1674);
};
SPOCK.run(t1673);
var t1761 = function (k807) {
 var t1762 = function (k808, t436) {	// open-close-switch
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1763 = function (t820) {
   var t437 = t820;
   var t438 = t437;
   var t1764 = null;
   var t439 = t1764;
   var t1765 = (t438) === (t439);
   var t809 = t1765;
   var t1766;
   if(t809 !== false) {
    var t1767 = function (k810, t440) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1768 = function (k811) {
      return ___tree_2dobj(k811, t436);
     };
     var t1770 = function (k812, t441) {
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t1771 = function (t814) {
       var t442 = t814;
       var t813 = t442;
       return ___send_2dvars(k812, t813);
      };
      var t1773 = SPOCK.intern("file-to-open");
      var t443 = t1773;
      var t444 = t441;
      var t1774 = new SPOCK.Pair(t443, t444);
      return ____25list(t1771, t1774);
     };
     return ___call_2dwith_2dvalues(k810, t1768, t1770);
    };
    return ___a_2dclick(k808, false, "+", t1767);
   }
   else {
    var t445 = ___children;
    var t1779 = SPOCK.intern("loading");
    var t446 = t1779;
    var t1780 = SPOCK.equalp(t445, t446);
    var t1778;
    if(t1780 !== false) {
     return k808("...");
    }
    else {
     var t1782 = function (k815, t447) {
      var r = SPOCK.count(arguments);
      if(r) return r;
      var t1783 = function (k816) {
       return ___tree_2dobj(k816, t436);
      };
      var t1785 = function (k817, t448) {
       var r = SPOCK.count(arguments);
       if(r) return r;
       var t1786 = function (t819) {
        var t449 = t819;
        var t818 = t449;
        return ___send_2dvars(k817, t818);
       };
       var t1788 = SPOCK.intern("file-to-close");
       var t450 = t1788;
       var t451 = t448;
       var t1789 = new SPOCK.Pair(t450, t451);
       return ____25list(t1786, t1789);
      };
      return ___call_2dwith_2dvalues(k815, t1783, t1785);
     };
     return ___a_2dclick(k808, false, "-", t1782);
    }
    t1766 = t1778;
   }
  };
  return ___tree_2dchildren(t1763, t436);
 };
 ___open_2dclose_2dswitch = t1762;	// set! open-close-switch
 var t1794 = function (k821, t452) {	// file-explorer
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1795;
  if(t452 !== false) {
   var t1796 = function (t854) {
    var t1797 = function(k1798, x) { return k1798(x.type); }
    var t1799 = function (t853) {
     var t453 = t853;
     var t454 = "dir";
     var t1800 = SPOCK.equalp(t453, t454);
     var t822 = t1800;
     var t1801;
     if(t822 !== false) {
      var t1802 = function (t838) {
       var t1803 = function (t823) {
        var t1804 = function (t825) {
         var t1805 = function (t826) {
          var t1806 = function (t837) {
           var t1807 = function (t828) {
            var t1808 = function (t829) {	// t830
             var t1809 = function (t827) {
              var t1810 = function (t824) {
               return ___h(k821, t823, false, t824);
              };
              return ___vector(t1810, t825, t826, t827);
             };
             return ___h(t1809, t828, false, t829);
            };
            var t830 = t1808;
            var t1814 = function (t836) {
             var t458 = t836;
             var t1815 = (t458) instanceof SPOCK.Pair ;
             var t833 = t1815;
             var t457 = t833;
             var t1816 = function (t831) {	// t834
              var t1817;
              if(t831 !== false) {
               var t1818 = function (t832) {
                return ___map(t830, ___file_2dexplorer, t832);
               };
               return ___tree_2dchildren(t1818, t452);
              }
              else {
               var t1821 = null;
               return t830(t1821);
              }
             };
             var t834 = t1816;
             var t1823;
             if(t457 !== false) {
              return t834(t457);
             }
             else {
              var t1825 = function (t835) {
               var t459 = t835;
               var t1826 = (t459) instanceof Array ;
               return t834(t1826);
              };
              return ___tree_2dchildren(t1825, t452);
             }
            };
            return ___tree_2dchildren(t1814, t452);
           };
           return ___jstring(t1807, t837);
          };
          var t456 = ".files";
          var t1831;
          if(t456 !== false) {
           t1831 = t456;
          }
          else {
           t1831 = "";
          }
          return ___string_2dappend(t1806, "ul", t1831);
         };
         return ___tree_2dpath(t1805, t452);
        };
        return ___open_2dclose_2dswitch(t1804, t452);
       };
       return ___jstring(t1803, t838);
      };
      var t455 = ".dir";
      var t1836;
      if(t455 !== false) {
       t1836 = t455;
      }
      else {
       t1836 = "";
      }
      return ___string_2dappend(t1802, "li", t1836);
     }
     else {
      var t1838 = function (t852) {
       var t1839 = function (t839) {
        var t1840 = function (t842) {
         var t1841 = function (t841) {
          var t1842 = function (t840) {
           return ___h(k821, t839, false, t840);
          };
          return ___vector(t1842, t841);
         };
         var t1845 = function (k843, t461) {
          var r = SPOCK.count(arguments);
          if(r) return r;
          var t1846 = function (t851) {
           var t1847 = function(k1848, x) { return k1848(x.url); }
           var t1849 = function (t844) {
            var t1850 = function (k845, t462) {
             var r = SPOCK.count(arguments);
             if(r) return r;
             var t1851 = function (k846) {
              var t1852 = function(k1853, x) { return k1853(x.content); }
              var t1854 = function (t847) {
               var t1855 = atob(t847);
               return k846(t1855);
              };
              return t1852(t1854, t462);
             };
             var t1858 = function (k848, t463) {
              var r = SPOCK.count(arguments);
              if(r) return r;
              var t1859 = function (t850) {
               var t464 = t850;
               var t849 = t464;
               return ___send_2dvars(k848, t849);
              };
              var t1861 = SPOCK.intern("file");
              var t465 = t1861;
              var t466 = t463;
              var t1862 = new SPOCK.Pair(t465, t466);
              return ____25list(t1859, t1862);
             };
             return ___call_2dwith_2dvalues(k845, t1851, t1858);
            };
            return ___github_2dapi_2dcall(k843, t844, t1850);
           };
           return t1847(t1849, t851);
          };
          return ___tree_2dobj(t1846, t452);
         };
         return ___a_2dclick(t1841, false, t842, t1845);
        };
        return ___tree_2dpath(t1840, t452);
       };
       return ___jstring(t1839, t852);
      };
      var t460 = false;
      var t1871;
      if(t460 !== false) {
       t1871 = t460;
      }
      else {
       t1871 = "";
      }
      return ___string_2dappend(t1838, "li", t1871);
     }
    };
    return t1797(t1799, t854);
   };
   return ___tree_2dobj(t1796, t452);
  }
  else {
   return k821(undefined);
  }
 };
 ___file_2dexplorer = t1794;	// set! file-explorer
 var t1876 = function (k855, t467) {
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t468 = t467;
  var t469 = undefined;
  var t1877 = function (t866) {
   t469 = t866;	// set! t469
   var t856 = undefined;
   var t1878 = function (t858) {
    var t475 = t858;
    var t1879 = function (t865) {
     var t1880 = function (t862) {
      var t1881 = function (t864) {
       var t1882 = function (t863) {
        var t1883 = function (t859) {
         var t476 = t859;
         var t1884 = function (t857) {	// t860
          return ___yield(k855);
         };
         var t860 = t1884;
         var t1886;
         if(t476 !== false) {
          var t1887 = function (t861) {
           t468 = t861;	// set! t468
           return t860(undefined);
          };
          return ___patch(t1887, t468, t476);
         }
         else {
          return t860(t468);
         }
        };
        return ___h(t1883, t862, false, t863);
       };
       return ___map(t1882, ___file_2dexplorer, t864);
      };
      return ___tree_2dchildren(t1881, t475);
     };
     return ___jstring(t1880, t865);
    };
    var t477 = false;
    var t1895;
    if(t477 !== false) {
     t1895 = t477;
    }
    else {
     t1895 = "";
    }
    return ___string_2dappend(t1879, "ul", t1895);
   };
   var t1897 = SPOCK.intern("files");
   return ___alist_2dref(t1878, t1897, t469);
  };
  var t1899 = function (k867, t470) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1900 = function (k869, t472) {	// t471
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t1901 = function (t870) {
     return t470(k869, t870);
    };
    return ___append(t1901, t472, t469);
   };
   var t471 = t1900;
   var t1904 = function (t873) {
    var t474 = t873;
    var t872 = t474;
    var t1905 = function (t868) {
     var t1906 = null;
     return k867(t1906);
    };
    var t1908 = function (k871, t473) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1909 = SPOCK.intern("continuations");
     return ___put_2dcons_21(k871, t473, t1909, t471);
    };
    return ___map(t1905, t1908, t872);
   };
   var t1912 = SPOCK.intern("files");
   return ____25list(t1904, t1912);
  };
  return ___call_2fcc(t1877, t1899);
 };
 return ___register_2dcomponent(k807, "explorer", t1876);
};
SPOCK.run(t1761);
var t1916 = function (k874) {
 var t1917 = function (k875, t478) {
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t479 = t478;
  var t480 = undefined;
  var t1918 = function (t884) {
   t480 = t884;	// set! t480
   var t876 = undefined;
   var t1919 = function (t878) {
    var t486 = t878;
    var t1920 = function (t883) {
     var t1921 = function (t882) {
      var t1922 = function (t879) {
       var t487 = t879;
       var t1923 = function (t877) {	// t880
        return ___yield(k875);
       };
       var t880 = t1923;
       var t1925;
       if(t487 !== false) {
        var t1926 = function (t881) {
         t479 = t881;	// set! t479
         return t880(undefined);
        };
        return ___patch(t1926, t479, t487);
       }
       else {
        return t880(t479);
       }
      };
      return ___h(t1922, t882, false, t486);
     };
     return ___jstring(t1921, t883);
    };
    var t488 = false;
    var t1932;
    if(t488 !== false) {
     t1932 = t488;
    }
    else {
     t1932 = "";
    }
    return ___string_2dappend(t1920, "pre", t1932);
   };
   var t1934 = SPOCK.intern("file");
   return ___alist_2dref(t1919, t1934, t480);
  };
  var t1936 = function (k885, t481) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1937 = function (k887, t483) {	// t482
    var r = SPOCK.count(arguments);
    if(r) return r;
    var t1938 = function (t888) {
     return t481(k887, t888);
    };
    return ___append(t1938, t483, t480);
   };
   var t482 = t1937;
   var t1941 = function (t891) {
    var t485 = t891;
    var t890 = t485;
    var t1942 = function (t886) {
     var t1943 = null;
     return k885(t1943);
    };
    var t1945 = function (k889, t484) {
     var r = SPOCK.count(arguments);
     if(r) return r;
     var t1946 = SPOCK.intern("continuations");
     return ___put_2dcons_21(k889, t484, t1946, t482);
    };
    return ___map(t1942, t1945, t890);
   };
   var t1949 = SPOCK.intern("file");
   return ____25list(t1941, t1949);
  };
  return ___call_2fcc(t1918, t1936);
 };
 return ___register_2dcomponent(k874, "editor", t1917);
};
SPOCK.run(t1916);
var t1953 = function (k892) {
 return ___log(k892, window.location.pathname);
};
SPOCK.run(t1953);
var t1955 = function (k893) {
 var t1956 = function (t894) {
  return ___map(k893, ___log, t894);
 };
 return ___get_2dpath(t1956);
};
SPOCK.run(t1955);
var t1959 = function (k895) {
 var t1960 = function (t898) {
  var t1961 = function (k896, t489) {
   var r = SPOCK.count(arguments);
   if(r) return r;
   var t1962 = t489.getAttribute("spock");
   var t490 = t1962;
   var t1963 = function (t897) {
    return t897(k896, t489);
   };
   return ___get_2dcallback(t1963, t490);
  };
  return ___map(k895, t1961, t898);
 };
 return ___spock_2delements(t1960);
};
SPOCK.run(t1959);
var t1968 = function (k899) {
 var t1969 = function (k900) {
  var t1970 = function (t901) {
   return ___values(k900, t901);
  };
  return ___get_2dhash(t1970);
 };
 var t1973 = function (k902, t491) {
  var r = SPOCK.count(arguments);
  if(r) return r;
  var t1974 = function (t904) {
   var t492 = t904;
   var t903 = t492;
   return ___send_2dvars(k902, t903);
  };
  var t1976 = SPOCK.intern("user");
  var t493 = t1976;
  var t494 = t491;
  var t1977 = new SPOCK.Pair(t493, t494);
  return ____25list(t1974, t1977);
 };
 return ___call_2dwith_2dvalues(k899, t1969, t1973);
};
SPOCK.run(t1968);
var t1980 = function (k905) {
 var t1981 = function (k906, t495) {
  var r = SPOCK.count(arguments);
  if(r) return r;
  loop: while(true) {
   ___waiting = t495;	// set! waiting
   return k906(undefined);
  }
 };
 return ___call_2fcc(k905, t1981);
};
SPOCK.run(t1980);
var t1984 = function (k907) {
 return ___print(k907, "waiting...");
};
SPOCK.run(t1984);
SPOCK.flush();
/* END OF GENERATED CODE */
